### ISSUE TITLE
Release Flatcar Container Linux Alpha 3572.0.1, Beta 3549.1.1, Stable 3510.2.1, LTS 3033.3.12 

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#1008]
## Release Flatcar Container Linux Alpha 3572.0.1, Beta 3549.1.1, Stable 3510.2.1, LTS 3033.3.12 
  
The release of Flatcar Container Linux Alpha 3572.0.1, Beta 3549.1.1, Stable 3510.2.1, LTS 3033.3.12  is planned for April 24th, 2023

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [link](https://hackmd.io/Egq-3KcvR-GbA8FIKHyqEw) (@sayanchowdhury)
- [x] Check that the kernel PR are merged for the channel(s) to be released. (@sayanchowdhury)
- [x] All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems (@sayanchowdhury)
~- [ ] Branch off main (only new major) ()~
- [x] Tag build branch (@sayanchowdhury)
- [x] Start Jenkins builds, post links as comment (@sayanchowdhury)
- [x] Test status captured in hackmd doc (@sayanchowdhury )
- [x] All tests are green (@sayanchowdhury )
- [x] Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None` (@sayanchowdhury )
- [x] QA: check diff for image file list, packages, and image size in the image job output (@sayanchowdhury )
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury )
- [x] Update payload signed/uploaded (@dongsupark)
- [x] `scripts` release created on GitHub (@sayanchowdhury )
- [x] Release job `container/release` ran (@sayanchowdhury )
- [x] Images uploaded with `copy-to-origin.sh` (@sayanchowdhury )
- [x] Azure offer updated & publishing started (@sayanchowdhury )
- [x] Azure Go Live (@sayanchowdhury )
- [x] GCP offers updated (@sayanchowdhury )
- [x] For new Stable: Manually run `./azure-sig.sh` to create new Shared Community Gallery Images (@sayanchowdhury )
- [x] For new Stable: build and provide images for supported Cluster API providers (@sayanchowdhury )
- [x] Symlink to "current" updated with `set-symlink.sh` (@sayanchowdhury )
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@sayanchowdhury )
- [x] Release package published in Nebraska (@dongsupark)
- [x] Send announcement to Mailing Lists (@sayanchowdhury )
- [x] Send Tweet out (@miao0miao, @ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel (@sayanchowdhury)

**Comment by sayanchowdhury** [comment]
Alpha: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1696/cldsv/
Beta: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1697/cldsv/
Stable: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1698/cldsv/
LTS: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1699/cldsv/

**Comment by sayanchowdhury** [comment]
Website PR: https://github.com/flatcar/flatcar-website/pull/265

**Comment by sayanchowdhury** [comment]
Marking the release as complete.
