### ISSUE TITLE
Release Flatcar Container Linux Alpha 3602.0.0 Beta 3572.1.0

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#1020]
## Release Flatcar Container Linux Alpha 3602.0.0 Beta 3572.1.0
  
The release of Flatcar Container Linux planned for May 15th, 2023

- Alpha 3602.0.0
- Beta 3572.1.0

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [link](https://hackmd.io/6b-1gNxUS4Wmta0TSVfzxQ) (@sayanchowdhury )
- [x] Check that the kernel PR are merged for the channel(s) to be released. (@sayanchowdhury )
- [x] All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems (@sayanchowdhury )
- [x] Branch off main (only new major) (@sayanchowdhury )
- [x] Tag build branch (@sayanchowdhury )
- [x] Start Jenkins builds, post links as comment (@sayanchowdhury )
- [x] Test status captured in hackmd doc (@sayanchowdhury)
- [x] All tests are green (@sayanchowdhury)
- [x] Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None` (@sayanchowdhury)
- [x] QA: check diff for image file list, packages, and image size in the image job output (@dongsupark)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury)
- [x] Update payload signed/uploaded (@dongsupark)
- [x] `scripts` release created on GitHub (@sayanchowdhury)
- [x] Release job `container/release` ran (@sayanchowdhury)
- [x] Images uploaded with `copy-to-origin.sh` (@sayanchowdhury)
- [x] Azure offer updated & publishing started (@sayanchowdhury )
- [x] Azure Go Live (@sayanchowdhury )
- [x] GCP offers updated (@sayanchowdhury )
- ~~For new Stable: Manually run `./azure-sig.sh` to create new Shared Community Gallery Images~~
- ~~For new Stable: build and provide images for supported Cluster API providers ()~~
- [x] Symlink to "current" updated with `set-symlink.sh` (@sayanchowdhury)
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@sayanchowdhury)
- [x] Release package published in Nebraska (@dongsupark)
- [x] Send announcement to Mailing Lists (@sayanchowdhury )
- [x] Send Tweet out (@ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel

**Comment by sayanchowdhury** [comment]
Alpha: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/801/cldsv/
Beta: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1816/cldsv/

**Comment by sayanchowdhury** [comment]
Flatcar website: https://github.com/flatcar/flatcar-website/pull/266

**Comment by sayanchowdhury** [comment]
Marking the release as complete.
