### ISSUE TITLE
Release Flatcar Container Linux Alpha 3619.0.0, Beta 3602.1.0, Stable 3510.2.2, LTS 3033.3.13

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#1041]
## Release Flatcar Container Linux Alpha 3619.0.0, Beta 3602.1.0, Stable 3510.2.2, LTS 3033.3.13
  
The release of Flatcar Container Linux is planned for June 1st, 2023

- Alpha 3619.0.0
- Beta 3602.1.0
- Stable 3510.2.2
- LTS 3033.3.13

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [link 1](https://hackmd.io/1CGDe77HS1SzizFZwW5jLQ?view), [link 2](https://hackmd.io/Rhav_jDVRk-FV2qo5gb1Ow?view), [link 3](https://hackmd.io/JmcQ7EyJTmOggUURf4Uk8A?view) (@dongsupark)
- [x] Check that the kernel PR are merged for the channel(s) to be released. (@dongsupark)
- [x] All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems (@sayanchowdhury )
- [x] Branch off main (only new major) (@sayanchowdhury )
- [x] Tag build branch (@sayanchowdhury )
- [x] Start Jenkins builds, post links as comment (@sayanchowdhury )
- [x] Test status captured in hackmd doc (@dongsupark)
- [x] All tests are green (@dongsupark)
- [x] Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None` (@dongsupark)
- [x] QA: check diff for image file list, packages, and image size in the image job output (@dongsupark)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@dongsupark)
- [x] Update payload signed/uploaded (@dongsupark)
- [x] `scripts` release created on GitHub (@dongsupark)
- [x] Release job `container/release` ran (@dongsupark)
- [x] Images uploaded with `copy-to-origin.sh` (@dongsupark)
- [x] Azure offer updated & publishing started (@tormath1)
- [x] Azure Go Live (@tormath1)
- [x] GCP Offer deployment package uploaded to Google bucket and submitted for verification ()
- [x] GCP Offer submit for verification ()
- [x] GCP Offer Publish ()
- [x] For new Stable: Manually run `./azure-sig.sh` to create new Shared Community Gallery Images (@tormath1)
- [x] For new Stable: build and provide images for supported Cluster API providers ()
- [x] Symlink to "current" updated with `set-symlink.sh` (@dongsupark)
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@dongsupark)
- [x] Release package published in Nebraska (@dongsupark)
- [x] Send announcement to Mailing Lists ()
- [x] Send Tweet out (@ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel (@dongsupark)

**Comment by sayanchowdhury** [comment]
Alpha 3619.0.0 http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/829/cldsv/
Beta 3602.1.0 http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1890/cldsv/
Stable 3510.2.2 http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1891/cldsv/
LTS 3033.3.13 http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1892/cldsv/

**Comment by dongsupark** [comment]
Done
