### ISSUE TITLE
Release Flatcar Container Linux Alpha 3637.0.0, Beta 3602.1.1, Stable 3510.2.3, LTS 3033.3.14

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#1075]
## Release Flatcar Container Linux Alpha 3637.0.0, Beta 3602.1.1, Stable 3510.2.3, LTS 3033.3.14
  
The release of Flatcar Container Linux June 19th, 2023

- Alpha 3637.0.0
- Beta 3602.1.1
- Stable 3510.2.3
- LTS 3033.3.14

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [link](https://hackmd.io/8JL2aHykTjyn-J4k_JN8gQ?both) (@sayanchowdhury)
- [x] Check that the kernel PR are merged for the channel(s) to be released. (@dongsupark )
- [x] All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems (@sayanchowdhury )
- [x] Branch off main (only new major) (@sayanchowdhury )
- [x] Tag build branch (@sayanchowdhury )
- [x] Start Jenkins builds, post links as comment (@sayanchowdhury )
- [x] Test status captured in hackmd doc (@sayanchowdhury )
- [x] All tests are green (@sayanchowdhury )
- [x] Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None` (@sayanchowdhury )
- [x] QA: check diff for image file list, packages, and image size in the image job output (@sayanchowdhury )
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury )
- [x] Update payload signed/uploaded (@dongsupark)
- [x] `scripts` release created on GitHub (@sayanchowdhury )
- [x] Release job `container/release` ran (@sayanchowdhury )
- [x] Images uploaded with `copy-to-origin.sh` (@dongsupark)
- [x] Azure offer updated & publishing started (@sayanchowdhury )
- [x] Azure Go Live (@sayanchowdhury )
- [x] GCP Offer deployment package uploaded to Google bucket and submitted for verification (@sayanchowdhury )
- [x] GCP Offer submit for verification (@sayanchowdhury )
- [x] GCP Offer Publish (@sayanchowdhury )
- [ ] For new Stable: Manually run `./azure-sig.sh` to create new Shared Community Gallery Images (@sayanchowdhury)
- [x] For new Stable: build and provide images for supported Cluster API providers (@sayanchowdhury ) (https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1594)
- [x] Symlink to "current" updated with `set-symlink.sh` (@dongsupark)
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@dongsupark)
- [x] Release package published in Nebraska (@dongsupark)
- [x] Send announcement to Mailing Lists (@sayanchowdhury )
- [x] Send Tweet out (@ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel (@sayanchowdhury)

**Comment by sayanchowdhury** [comment]
Alpha 3637.0.0 http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/866/cldsv/
Beta 3602.1.1 http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/2007/cldsv/
Stable 3510.2.3 http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/2008/cldsv/
LTS 3033.3.14 http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/2009/cldsv/

On going issues:
- https://github.com/flatcar/scripts/pull/936
- https://github.com/flatcar/scripts/pull/935
- cloudinit issue with DO (https://github.com/flatcar/coreos-cloudinit/pull/22 & https://github.com/flatcar/scripts/pull/937)

**Comment by sayanchowdhury** [comment]
Marking the issue as complete.
