### ISSUE TITLE
Release Flatcar Container Linux Alpha 3654.0.0, Beta 3602.1.2, Stable 3510.2.4

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#1106]
## Release Flatcar Container Linux Alpha 3654.0.0, Beta 3602.1.2, Stable 3510.2.4
  
The release of Flatcar Container Linux of the following version is planned for July 4th, 2023. 

- Alpha 3654.0.0 
- Beta 3602.1.2
- Stable 3510.2.4

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [link](https://hackmd.io/thYlqweJSsOEhpjLvlv48Q?view) (@dongsupark )
- [x] Check that the kernel PR are merged for the channel(s) to be released. (@dongsupark )
- [x] All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems (@dongsupark )
- [x] Branch off main (only new major) (@dongsupark )
- [x] Tag build branch (@dongsupark )
- [x] Start Jenkins builds, post links as comment (@dongsupark)
- [x] Test status captured in hackmd doc (@sayanchowdhury)
- [x] All tests are green (@sayanchowdhury)
- [x] Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None` (@dongsupark )
- [x] QA: check diff for image file list, packages, and image size in the image job output (@dongsupark)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury)
- [x] Update payload signed/uploaded (@dongsupark)
- [x] `scripts` release created on GitHub (@sayanchowdhury)
- [x] Release job `container/release` ran (@sayanchowdhury)
- [x] Images uploaded with `copy-to-origin.sh` (@sayanchowdhury)
- [x] Azure offer updated & publishing started (@tormath1)
- [x] Azure Go Live (@tormath1)
- [x] GCP Offer deployment package uploaded to Google bucket and submitted for verification ()
- [x] GCP Offer submit for verification ()
- [x] GCP Offer Publish ()
- [x] For new Stable: Manually run `./azure-sig.sh` to create new Shared Community Gallery Images (@pothos)
- [x] For new Stable: build and provide images for supported Cluster API providers (@tormath1 for CAPO: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1607)
- [x] Symlink to "current" updated with `set-symlink.sh` (@sayanchowdhury)
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@sayanchowdhury)
- [x] Release package published in Nebraska (@dongsupark)
- [x] Send announcement to Mailing Lists (@sayanchowdhury)
- [x] Send Tweet out (@ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel (@sayanchowdhury)

**Comment by dongsupark** [comment]
* Alpha 3654.0.0: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/896/cldsv/
* Beta 3602.1.2 http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/2101/cldsv/
* Stable 3510.2.4 http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/2100/cldsv/

**Comment by sayanchowdhury** [comment]
Flatcar website PR: https://github.com/flatcar/flatcar-website/pull/270

**Comment by sayanchowdhury** [comment]
Marking the release as Complete 🎉
