### ISSUE TITLE
[Tracking]: Docker 25 drops devicemapper storage driver

### ISSUE THREAD

**Issue by krnowak** [flatcar/Flatcar#1360]
We haven't yet updated docker to version 25, but I tried doing it last week. Kola test checking for devicemapper storage driver failed, so went with latest 24 patch release instead.

- [x] update docker to 25 (https://github.com/flatcar/scripts/pull/2152)
- [x] update kola devicemapper storage driver test to run until some version (https://github.com/flatcar/mantle/pull/542) 
- [x] yell in changelogs, release notes and everywhere about device mapper going away on Flatcar really soon
- [ ] anything else?

**Comment by krnowak** [comment]
See https://docs.docker.com/engine/deprecated/#device-mapper-storage-driver

**Comment by t-lo** [comment]
I've started tracking Docker upgrade status in our flatcar dev syncs and added a section to the agenda template that also discusses what's being removed. Docker 27 is out so actually we could upgrade to 27 directly...

https://github.com/flatcar/Flatcar/discussions/1486

**Comment by tormath1** [comment]
Done here: https://github.com/flatcar/scripts/pull/2152
