### ISSUE TITLE
[Tracking] Flatcar support on Akamai Connected Cloud (a.k.a. Linode)

### ISSUE THREAD

**Issue by nesv** [flatcar/Flatcar#1404]
This issue is for tracking support for supporting Flatcar on Akamai Connected Cloud (previously known as "Linode").

- [x] Implement Ignition support &mdash; https://github.com/coreos/ignition/issues/1508
- [x] Implement Afterburn support &mdash; https://github.com/coreos/afterburn/pull/1062
- [x] Pull Ignition v2.19.0 (https://github.com/coreos/ignition/issues/1876, https://github.com/flatcar/scripts/pull/2019)
- [x] Pull Afterburn v5.5.2 (https://github.com/coreos/afterburn/issues/1076, https://github.com/flatcar/scripts/pull/2041)
- [x] OEM support on Flatcar https://github.com/flatcar/scripts/pull/1806
- [x] Provide user documentation &mdash; https://github.com/flatcar/flatcar-website/pull/327
- [x] Implement a test suite using [github.com/linode/linodego](https://pkg.go.dev/github.com/linode/linodego): https://github.com/flatcar/mantle/pull/567
- [x] Run test automation for the new provider before each release (https://github.com/flatcar/scripts/pull/2873)

**Comment by tormath1** [comment]
Ignition and Afterburn PRs are merged. Let's wait for both releases before pulling them here: https://github.com/flatcar/scripts/pull/1806

**Comment by tormath1** [comment]
Live demo has been done in the last office hours: https://www.youtube.com/live/i04yEYnDujg?feature=shared&t=295 thanks to @nesv  
The current status of the support is now:
- wait for the Afterburn release (https://github.com/coreos/afterburn/issues/1076#issuecomment-2163353183)
- or go ahead with a partial support in the next release (Ignition, OEM support but no Afterburn)

**Comment by tormath1** [comment]
On the development side, everything has been merged - Akamai official images should be available in the next release. During tests, we noticed two issues with @nesv:
* `/v1/ssh-keys` returns nothing on the image, seems to be because it's a private image (to be confirmed): https://www.linode.com/community/questions/24938/v1ssh-keys-is-empty-when-deploying-a-private-image
* Ignition delivery is sometimes failing: https://github.com/coreos/ignition/pull/1893

Both of these issues do not seem to be Flatcar related at the moment.

**Comment by tormath1** [comment]
Terraform example with Kubernetes deployment using Flatcar and systemd-sysext: https://github.com/flatcar/flatcar-terraform/pull/28 - CI tests automation will follow.

**Comment by tormath1** [comment]
The last bit has been implemented: the CI test automation. It closes this issue and make Akamai/Linode images officially supported. Many thanks to everyone involved on this journey. :heart:
