### ISSUE TITLE
[spike] upgrade to OpenSSL v3 to begin fixing everything that break

### ISSUE THREAD

**Issue by vbatts** [flatcar/Flatcar#418]
## Current situation

We have the OpenSSL v1.1.1 series in flatcar, 
and upstream OpenSSL (after 15+ alpha releases) have finally had their first [beta1 release candidate](https://www.openssl.org/blog/blog/2021/06/17/OpenSSL3.0ReleaseCandidate/).

## Impact

This brings flexibility to additional features flatcar can enable.

This will likely break, or fail to build a number of tools that link against libcrypto or libssl. Use this issue as a tracker for these, and open issues for each component to be addressed.

https://www.openssl.org/docs/man3.0/man7/migration_guide.html

**Comment by tormath1** [comment]
I will update this ticket with progresses:

* Packages with `dev-libs/openssl` dependency:
- [ ] net-misc/openssh
- [ ] net-misc/ntp
- [ ] net-analyzer/tcpdump
- [ ] sys-fs/cryptsetup
- [ ] dev-lang/python (https://bugs.python.org/issue38820)
- [ ] net-analyzer/nmap
- [ ] app-crypt/trousers
- [ ] app-admin/sudo
- [ ] app-arch/libarchive
- [ ] sys-block/open-isns
- [ ] net-misc/curl
- [ ] net-nds/openldap
- [ ] sys-auth/sssd
- [ ] net-misc/wget
- [ ] net-dns/bind-tools
- [ ] net-misc/rsync
- [ ] app-crypt/mit-krb5
- [ ] sys-block/open-iscsi
- [ ] dev-libs/cyrus-sasl
- [ ] dev-vcs/git

* Packages with failing build:

  - dev-python/cryptography (removed in: https://github.com/flatcar-linux/portage-stable/pull/219)
  - app-crypt/efitools (patched in: https://github.com/flatcar-linux/coreos-overlay/pull/1305)

**Comment by vbatts** [comment]
thanks for this, @tormath1

**Comment by vbatts** [comment]
due to the way OpenSSL have refactored the project as it relates to the FIPS canister.
If we can upgrade to v3, then it will be much easier for users of Flatcar to boot into fips_mode, and then this openssl v3 just does the FIPS thing

**Comment by vbatts** [comment]
[OpenSSL v3.0.0 is released](https://www.openssl.org/news/openssl-3.0-notes.html)

**Comment by vbatts** [comment]
added https://www.openssl.org/docs/man3.0/man7/migration_guide.html to the opening post

**Comment by tormath1** [comment]
update:
* `update_engine` is not fully compatible with `OpenSSLv3`, see: https://github.com/flatcar-linux/Flatcar/issues/519
* `dev-python/cryptography` does not build as expected but it has been removed in https://github.com/flatcar-linux/portage-stable/pull/219
* `afterburn` needs to upgrade its openssl dependencies: https://github.com/flatcar-linux/coreos-overlay/pull/1315
* `coreos.locksmith.tls` does not pass because it fails to generate certificates - an issue has been opened (https://github.com/openssl/openssl/issues/16720)
```
sudo /usr/bin/openssl x509 -extfile /etc/ssl/etcd.cnf -CA /etc/ssl/certs/ca-etcd-cert.pem -CAkey /etc/ssl/certs/ca-etcd-key.pem -CAcreateserial -sha512 -days 3 -in /etc/ssl/certs/etcd-cert-self.pem -out /etc/ssl/certs/etcd-cert.pem
subject=CN = localhost
Error with certificate - error 20 at depth 0
unable to get local issuer certificate
subject=CN = localhost
Error with certificate - error 21 at depth 0
unable to verify the first certificate
Error with certificate to be certified - should be self-signed
```

**Comment by tormath1** [comment]
OpenSSL-3.0.0 has been merged into `main` and will be soon available in `Alpha` channel. I notified that FIPS module is not built by default: https://bugs.gentoo.org/820173 an issue has been opened upstream to conditionally build FIPS via `fips` internal USE flag.
