### ISSUE TITLE
Simplify SDK format and distribution

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#441]
**Issue**
- Installing an SDK release uses custom logic
- After installing, SDK needs to be "initialised" for each board

**Impact**
- SDK target toolchains are not contained in SDK by default
- SDK is not portable; Installing custom-built SDK outside build infrastructure very hard / undocumented
- Reproducing CI builds outside CI very complex, next to impossible

**TODOs**
- [x] SDK is provided in a portable way as a container image
- [ ]  SDK image is signed
- [x] Releases can be switched (binary packages, coreos-overlay, and portage-stable) easily by checking out respective release tag
- [ ] CI `kola` tests use the SDK container / container build artefacts for running tests
- [x] CI publishes OS package binaries and images from containerised builds 
- [x] Documentation for [SDK](https://www.flatcar-linux.org/docs/latest/reference/developer-guides/sdk-modifying-flatcar/) and [image building](https://www.flatcar-linux.org/docs/latest/reference/developer-guides/sdk-building-production-images/) is updated

**Comment by t-lo** [comment]
WIP PR (just a start for now) is at https://github.com/kinvolk/flatcar-scripts/pull/147.

**Comment by t-lo** [comment]
- SDK container can build everything the regular SDK can
- Switching between releases (by release version) is implemented
That's 2 of 4 :)

**Comment by t-lo** [comment]
Updated the issue summary to reflect the current state: SDK container work has been merged and SDK container is available for development, but CI needs more work.

**Comment by jepio** [comment]
For the most part done, we'll create smaller follow-up issues when we tackle the remaining items.
