### ISSUE TITLE
Cluster-API: upstream support for most common providers

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#445]
### Support Flatcar in Cluster-API

***Tracked Issues and PRs***
**Foundational**
- [x]  Kubeadm Bootstrap provider ignition support: https://github.com/kubernetes-sigs/cluster-api/pull/4172
   - Related / `dataurl` dependency: https://github.com/vincent-petithory/dataurl/issues/7
- [X] Image Builder support for Flatcar: https://github.com/kubernetes-sigs/image-builder/pull/248
- [x] https://github.com/kubernetes-sigs/image-builder/pull/701

**Platforms / Providers**
- AWS: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1979
  - Blocked by [Ignition bootstrap PR](https://github.com/kubernetes-sigs/cluster-api/pull/4172) 
  - [x] Support ignition for bootstrapping: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2271 
- Azure: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/629 ( [downstream tracking issue](https://github.com/kinvolk/clusterapi-flatcar/issues/58) )
  - Blocked by [Ignition bootstrap PR](https://github.com/kubernetes-sigs/cluster-api/pull/4172) 
  - [ ] Add Flatcar Container Linux template to CAPZ: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1729
  - [x] Support for Shared Image Gallery images requiring a Plan : https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1463 , https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1469
  - [x] image-builder: support for Azure SIG flatcar image  https://github.com/kubernetes-sigs/image-builder/pull/652
  - [x] TODO: update azure go library in [Mantle](https://github.com/kinvolk/mantle) to support unmanaged disk images. Fallout of https://github.com/kinvolk/Flatcar/issues/417
- Equinix Metal:
  - [ ] Upstream PR for v1alpha4/v1beta1 support https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/289
  - [ ] WIP: template + metadata injection work needed
- Metal3:
  - [X] Support for Flatcar images: https://github.com/metal3-io/metal3-dev-env/pull/457
  - [ ] CAPI provider supports Flatcar: https://github.com/metal3-io/cluster-api-provider-metal3
- Tinkerbell
- vSphere
  - [x] https://github.com/kubernetes-sigs/image-builder/pull/817 VSphere Image builder support for Flatcar (blocked by below)
  - [x] https://github.com/kubernetes-sigs/image-builder/pull/827 
  - [x] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1429 Ignition support for VSphere
- GCP
  -  Tracking issue: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/540

**Tests**
-  https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-aws 
- https://prow.k8s.io/?repo=kubernetes-sigs%2Fcluster-api-provider-aws 

SIG cluster lifecycle meetings calendar: https://calendar.google.com/calendar/u/0/embed?src=u5822lrl4q68ic1iakuvcpe7b4@group.calendar.google.com

### Follow-up work (not checkboxed since it does not contribute to the roandmap item)
1. Publish a blog post on our changes and additions to CAPI to make Ignition and Flatcar work.
2. Integrate into the release process and publish Flatcar CAPI images on [Azure](https://github.com/devigned/pub) and AWS.
3. AWS provider: For Ignition support to graduate out of experimental phase we need to abstract out S3 support into a separate CRD, ref: [issue comment](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2271#discussion_r733584491).

**Comment by t-lo** [comment]
@dongsupark The Azure image-builder PR is still failing a test (containerd version detection), can you help? https://github.com/kubernetes-sigs/image-builder/pull/652

**Comment by surajssd** [comment]
@t-lo I don't have access to edit the issue comment. But for Ignition support to graduate out of experimental phase we need to abstract out S3 support into a separate CRD, ref: [issue comment](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2271#discussion_r733584491).

**Comment by till** [comment]
I would contribute openstack related support, if there is any interest?

**Comment by t-lo** [comment]
@till There absolutely is! Please pardon the late reply. We're basing the support for individual providers on our work to support Ignition config as an alternative to cloud-init [in the kubeadm bootstrap provider](https://github.com/kubernetes-sigs/cluster-api/pull/4172); that's a good point to start.

**Comment by till** [comment]
@t-lo No worries.

Is this ultimately replacing the work in lokomotive? I hacked around in it to add Openstack, but wasn't able to gain any quick wins.

**Comment by t-lo** [comment]
> Is this ultimately replacing the work in lokomotive?
> I hacked around in it to add Openstack, but wasn't able to gain any quick wins.

It's not related to Lokomotive; CAPI and Lokomotive have different use cases.

**Comment by t-lo** [comment]
@till The PR to add Ignition support to kubeadm was merged and will be part of the CAPI v1.1 release next year. That's a good point in time to get started with Openstack support ;)
Please feel free to ping us here if you have questions.

**Comment by johananl** [comment]
I'm looking into vSphere support.

**Comment by ericgraf** [comment]
@t-lo If possible we would like to have support for GCP and OpenStack added to the supported provider list.

**Comment by t-lo** [comment]
@ericgraf Ignition support was added in the v1.1 CAPI release yesterday, making it significantly easier to add support for more providers. While we currently don't have plans to work on GCP or OpenStack please feel free to pick this up, I'll happily update the tracking issue to reflect the work.
Please do not hesitate to reach out to us for pointers and for help - the maintainers are available all day via https://app.element.io/#/room/#flatcar:matrix.org.

**Comment by srm09** [comment]
Adding @johananl 's PR for vSphere support here: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1429

**Comment by AverageMarcus** [comment]
@t-lo FYI I've opened an issue on CAPG to request Flatcar support - https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/540

**Comment by t-lo** [comment]
@AverageMarcus Thank you! I've added the tracking issue to the summary.

**Comment by t-lo** [comment]
@AverageMarcus Would you be interested to work on CAPG support? The team is supportive of the idea but currently pursues other priorities. We can definitely ramp you up on existing CAPI work and support you in the process.

**Comment by AverageMarcus** [comment]
I can't currently as have other work with higher priorities but possibly in the future once this becomes more of a priority for us. I mainly wanted to ensure it was tracked on CAPG so there was at least an awareness of wanting this.

**Comment by invidian** [comment]
Happy to ping everyone informing that CAPA support has been merged today :tada:

**Comment by kopiczko** [comment]
@t-lo I opened an issue for openstack https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1261. I'm working on this currently.

**Comment by kopiczko** [comment]
There will be changes required to the image-builder as well. Currently I'm basing my work on the QEMU image but grub.cfg requires modification. There is also a WIP PR to fix ongoing issues with the build https://github.com/kubernetes-sigs/image-builder/pull/907

**Comment by t-lo** [comment]
> There will be changes required to the image-builder as well. Currently I'm basing my work on the QEMU image but grub.cfg requires modification. There is also a WIP PR to fix ongoing issues with the build [kubernetes-sigs/image-builder#907](https://github.com/kubernetes-sigs/image-builder/pull/907)

Please feel free to reach out if you feel stuck. @pothos and @dongsupark are good peers for Flatcar related image builder issues, and @johananl did quite some work on image builder lately, too.

**Comment by t-lo** [comment]
We'll soon retire this epic tracking issue in favour of our new ClusterAPI tab in our Projects board: https://github.com/orgs/flatcar/projects/7/views/14

**Comment by johananl** [comment]
Everything was migrated to the [board](https://github.com/orgs/flatcar/projects/7/views/14) 🎉. Closing.
