### ISSUE TITLE
Move Flatcar repositories and website (back) to its own Github org

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#452]
Revive the [flatcar-linux github org](https://github.com/flatcar-linux/) as the go-to point for everything Flatcar Linux.

**Items**
- [x] Move repositories from kinvolk org back to flatcar-linux
- [x] Use Github pages for Flatcar website, Docs ([http://flatcar-linux.org](http://flatcar-linux.org)), adjust nameserver entries accordingly
- [x] consider retiring stale repos (rkt, appc/spec, acbuild, moby, etc.) instead of moving
- [x] Move or recreate release and roadmap boards

**Comment by vbatts** [comment]
oh good. I was just coming to create this issue, but you've already got it tracked.
A couple of things shake out of this. 

Here are the list of [flatcar repos](https://github.com/search?q=topic%3Aflatcar+org%3Akinvolk&type=Repositories) to split out. Some we actually merged with existing kinvolk repos, like the fork of the linux kernel. (flatcar one is used for tags of releases, and kinvolk one was used to stage upstream contributions).

**Comment by vbatts** [comment]
Also, I think we're close on getting the website portion done. @joaquimrocha and @sayanchowdhury were recently reviewing that.

**Comment by vbatts** [comment]
re docs: I would love for the docs to just use github pages.

For that matter, it almost seems that most of the flatcar page could be statically served up there, and not need an outside service 🤔

**Comment by joaquimrocha** [comment]
I agree for the flatcar page hosting (because we can add a custom domain).
As for the docs, would it be hosted then in "inspektor-gadget.github.io" or "inspektor-gadget.github.io/docs" ? The URL is not great, I mean.

**Comment by vbatts** [comment]
I recall seeing subdomains possible. Per your example "docs.inspektor-gadget.github.io"

**Comment by tormath1** [comment]
I think this issue is mainly done.
> Use Github pages for Flatcar website, Docs (http://flatcar-linux.org/), adjust nameserver entries accordingly

Is it still something we want to do?

**Comment by pothos** [comment]
We could set it up in parallel and eventually migrate the domain when needed: https://gohugo.io/hosting-and-deployment/hosting-on-github/#branches-for-github-actions

**Comment by sayanchowdhury** [comment]
@pothos @tormath1 Let's close and open a new for the domain migration?
