### ISSUE TITLE
[Tracking] SPDX License headers in source files of repos

### ISSUE THREAD

**Issue by dongsupark** [flatcar/Flatcar#567]
So far in most Flatcar repos, each source file has a common form of copyright headers like:

```
// Copyright 2021 Kinvolk GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
```

We should make the header community-friendly and consistent all over the repo.

* If possible, use a neutral term to cover all other authors, instead of Kinvolk. Ideally "Copyright The [project name] Authors".
  - We should not specify years, for simplifying maintenance in the future.
  - Keep original copyright statements if they exist.
* Use SPDX License Identifier, instead of having License terms per source file.
* Make sure a `LICENSE` file on the top-level source directory is correct w.r.t. the SPDX License.
* Avoid using different copyright headers in different files, unless if that is necessary.

For example, each file has a header like that:

```
// Copyright The project_name Authors
// SPDX-License-Identifier: Apache-2.0
```

Repos with Apache 2:

- [ ] https://github.com/flatcar-linux/afterburn
- [ ] https://github.com/flatcar-linux/container-linux-config-transpiler
- [ ] https://github.com/flatcar-linux/coreos-cloudinit
- [ ] https://github.com/flatcar-linux/flatcar-build-scripts
- [ ] https://github.com/flatcar-linux/flatcar-linux-update-operator
- [ ] https://github.com/flatcar-linux/flatcar-packer-qemu
- [ ] https://github.com/flatcar-linux/ignition
- [ ] https://github.com/flatcar-linux/locksmith
- [x] https://github.com/flatcar-linux/mantle (https://github.com/flatcar-linux/mantle/pull/263)
- [ ] https://github.com/flatcar-linux/mayday
- [ ] https://github.com/flatcar-linux/sdnotify-proxy
- [ ] https://github.com/flatcar-linux/torcx
- [ ] https://github.com/flatcar-linux/toolbox
- [ ] https://github.com/flatcar-linux/update-ssh-keys
- [ ] https://github.com/flatcar-linux/updateservicectl

Repos with MIT:
- [ ] https://github.com/flatcar-linux/flatcar-release-mirror
- [ ] https://github.com/flatcar-linux/flatcar-terraform
- [ ] https://github.com/flatcar-linux/fleetlock
- [ ] https://github.com/flatcar-linux/flog

Repos with BSD or similar:

- [ ] https://github.com/flatcar-linux/bootengine (CoreOS)
- [ ] https://github.com/flatcar-linux/efunctions (Marcus Downing)
- [ ] https://github.com/flatcar-linux/flatcar-dev-util (Chromiums)
- [ ] https://github.com/flatcar-linux/init  (CoreOS and ChromiumOS)
- [ ] https://github.com/flatcar-linux/scripts  (CoreOS and ChromiumOS)
- [ ] https://github.com/flatcar-linux/seismograph (ChromiumOS)
- [ ] https://github.com/flatcar-linux/shim (Matthew Garrett)
- [ ] https://github.com/flatcar-linux/update_engine (ChromiumOS)

Repos with GPL or LGPL:
- [ ] https://github.com/flatcar-linux/baselayout
- [ ] https://github.com/flatcar-linux/fero
- [ ] https://github.com/flatcar-linux/grub
- [ ] https://github.com/flatcar-linux/nss-altfiles
- [ ] https://github.com/flatcar-linux/sysroot-wrappers

**Comment by dongsupark** [comment]
Not needed any more, closing
