### ISSUE TITLE
Community Call 2021-12-14

### ISSUE THREAD

**Issue by miao0miao** [flatcar/Flatcar#571]
## TODO list for the meeting
  - [x] 1 week before meeting: Create Agenda PR @miao0miao - https://github.com/flatcar-linux/Flatcar/pull/572
  - [x] 1 week before meeting: Tweet "ask for input" @ahrkrak w/ link to agenda PR (so people can add topcis) - https://twitter.com/flatcar/status/1469250375513485312
  - [x] Monday before meeting: Finish and merge Agenda @miao0miao
  - [x] Monday before meeting: Tweet announcement @ahrkrak
  - [x] 1h before meeting: announce in matrix (w/ Zoom link) @t-lo 
  - [x] Start meeting, add recording link to agenda @miao0miao
  - [x] conduct meeting @flatcar-linux/flatcar-maintainers 
  - [x] after meeting, add slides (PDF) to agenda @[owner]

**Comment by tormath1** [comment]
@miao0miao this community call is over, I guess we can close this issue ? :)

**Comment by t-lo** [comment]
The slides [have not been published](https://github.com/flatcar-linux/Flatcar/tree/main/community-meetings) (even though the item was checked off).

**Comment by tormath1** [comment]
@t-lo slides have been pushed: https://github.com/flatcar-linux/Flatcar/commit/119080687b7e16e3326a27d5317f06ea8f304edf. Checking the item :)

**Comment by t-lo** [comment]
Awesome, thanks for jumping in @tormath1 ! We're done here, closing the issue.
