### ISSUE TITLE
Community Call 2022-01-11

### ISSUE THREAD

**Issue by miao0miao** [flatcar/Flatcar#589]
## TODO list for the meeting
  - [x] 1 week before meeting: Create Agenda PR @miao0miao (https://github.com/flatcar-linux/Flatcar/discussions/594)
  - [x] 1 week before meeting: Tweet "ask for input" @ahrkrak  w/ link to agenda PR (so people can add topcis)
  - [ ] Monday before meeting: Finish and merge Agenda @miao0miao 
  - [ ] Monday before meeting: Tweet announcement @ahrkrak 
  - [ ] 1h before meeting: announce in matrix (w/ Zoom link) @miao0miao 
  - [ ] Start meeting, add recording link to agenda @miao0miao 
  - [ ] conduct meeting @miao0miao 
  - [ ] after meeting, add slides (PDF) to agenda @miao0miao

**Comment by t-lo** [comment]
@miao0miao Please review https://github.com/flatcar-linux/Flatcar/pull/610 to get this issue closed.
