### ISSUE TITLE
Release Flatcar Container Linux Alpha 3115.0.0

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#595]
Planned release on January 13th, 2022. 

### Tasks
- [x] Go / No Go tracking folder created, tracking doc added (@sayanchowdhury)
- [x] All planned changes are merged & blocker bugs are fixed (@sayanchowdhury)
- [x] Branch off main (only new major) (@sayanchowdhury)
- [x] Tag build branch (@sayanchowdhury)
- [x] Generate manifest (@sayanchowdhury)
- [x] Start Jenkins builds (@sayanchowdhury)
- [x] Test status captured in test status tracker (@sayanchowdhury)
- [x] All tests are green (@sayanchowdhury)
- [x] Archive TAP report, create Go / No Go doc (@sayanchowdhury)
- [x] Release notes / announcements added to Go/No Go doc (@sayanchowdhury)
- [x] QA: check diff for image file list, packages, and image size (@pothos)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury)
- [x] Manifest release created on GitHub (@sayanchowdhury)
- [x] Update the SDK release metadata for new major Alpha releases with SDK builds (only new major) (@sayanchowdhury)
- [x] Images uploaded (@sayanchowdhury)
- [x] Run the `os/release` job (@sayanchowdhury)
- [x] Publish EC2 Marketplace Images (Submit for scanning) (@tormath1)
- [x] Publish EC2 Marketplace Images (Update Product) (@tormath1)
- [x] Azure offer updated & publishing started (@sayanchowdhury)
- [x] Azure Go Live (@sayanchowdhury)
- [x] GCP offers updated (@sayanchowdhury)
- [x] Update payload signed/published (@dongsupark)
- [x] Symlink to "current" updated (@sayanchowdhury)
- [x] Website updated (@sayanchowdhury)
- [x] Update CloudFormation templates (@sayanchowdhury)
- [x] Release package published in Nebraska (@dongsupark)
- [x] Send announcement to Mailing Lists, and tweet out! (@miao0miao)

**Comment by sayanchowdhury** [comment]
- Go/No-Go Document: https://hackmd.io/_bwDRdW7Roa7cc8tuJp7EQ
- Manifest Release Tag: https://github.com/kinvolk/manifest/releases/tag/v3115.0.0
- SDK Release Metadata Update PR: 
   * https://github.com/kinvolk/manifest/pull/47
   * https://github.com/flatcar-linux/scripts/pull/216

**Comment by pothos** [comment]
Founds these unwanted files added to the image content list, need to check if they are really on the image:
```
+/final
 /home
 /home/core
 /home/core/.bash_logout -> ../../usr/share/skel/.bash_logout
@@ -471,7 +474,17 @@
 /lib64 -> usr/lib64
 /lib -> lib64
 /lost+found
+/mcs
+/mcs/active
+/mcs/active/modules
+/mcs/semanage.read.LOCK
+/mcs/semanage.trans.LOCK
 /media
+/mls
+/mls/active
+/mls/active/modules
+/mls/semanage.read.LOCK
+/mls/semanage.trans.LOCK
 /mnt
 /opt
 /opt/bin
@@ -483,6 +496,11 @@
 /run/samba
 /sbin -> usr/sbin
 /sys
+/targeted
+/targeted/active
+/targeted/active/modules
+/targeted/semanage.read.LOCK
+/targeted/semanage.trans.LOCK
```

Image size diff is positive, we have a small reduction compared to 3066.0.0.

**Comment by pothos** [comment]
We can add this in the "Known Issues", also created an issue for it https://github.com/flatcar-linux/Flatcar/issues/596

**Comment by pothos** [comment]
Added it to https://hackmd.io/_bwDRdW7Roa7cc8tuJp7EQ?view

**Comment by sayanchowdhury** [comment]
We had some hiccups with the Azure publishing but that is now resolved. Marking the release as complete.
