### ISSUE TITLE
Release Team Call 2021-01-25

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#600]
## TODO list for the meeting
  - [x] 1 week before meeting: Create Agenda on [Github Discussion](https://github.com/flatcar-linux/Flatcar/discussions/601) board @sayanchowdhury 
  - [x] 1 week before meeting: Tweet "Invitation to Release Team Call w/ link to agenda discussion" (so people can add topics)
  - [x] Monday before meeting: Finish and merge Agenda @sayanchowdhury 
  - [x] Monday before meeting: Tweet announcement @ahrkrak
  - [x] 1h before meeting: announce in matrix (w/ Zoom link) @sayanchowdhury 
  - [x] Start meeting, add recording link to agenda @miao0miao 
  - [x] conduct meeting @sayanchowdhury 
  - [x] after meeting, add slides (PDF) to agenda @sayanchowdhury

**Comment by sayanchowdhury** [comment]
The agenda for the meeting is put up on the Github Discussion https://github.com/flatcar-linux/Flatcar/discussions/601

**Comment by jepio** [comment]
We can close this right?
