### ISSUE TITLE
Handling CVE-2022-0185

### ISSUE THREAD

**Issue by xamroc** [flatcar/Flatcar#602]
Recently this CVE was published: https://sysdig.com/blog/cve-2022-0185-container-escape/

We should be able to mitigate this by setting the following:
`sysctl -w kernel.unprivileged_userns_clone = 0`

However, upon looking into Flatcar's variables, `kernel.unprivileged_userns_clone` is neither set nor defined. I did not find any reference to the docs about this variable. Is it recommended to set this variable? Or is there an alternative like an upgrade to mitigate this vulnerability?

Thanks!

**Comment by jepio** [comment]
`kernel.unprivileged_userns_clone` is a downstream Ubuntu/Debian patch, this is not available in Flatcar. The sysctl referenced for RedHat `user.max_user_namespaces = 0`, is present in upstream kernels, you may set that value if you wish.
The bug has been fixed by this commit https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=722d94847de29310e8aa03fcbdb41fc92c521756, which has been backported to stable kernels 5.15.16, and 5.10.93. These might be part of the next Flatcar releases, check these PRs:
- [x] flatcar-linux/coreos-overlay#1586
- [x] flatcar-linux/coreos-overlay#1582
- [x] flatcar-linux/coreos-overlay#1585
- [x] flatcar-linux/coreos-overlay#1583

**Comment by pothos** [comment]
While `sudo sysctl user.max_user_namespaces=0` forbids the creation of user namespaces even from the root user (a test is `sudo -u (core|root) unshare -U whoami`) it does not really mitigate the vulnerability for untrusted containers that are running with the root user and the SYS_ADMIN capability (but with that [capability](https://man7.org/linux/man-pages/man7/capabilities.7.html) the container could already harm the system in other ways).

**Comment by TheKangaroo** [comment]
I don't get when this will be released on https://www.flatcar.org/releases/ .
The MRs bump e.g. from kernel 5.10.92 to 5.10.93, but the release page says 3033/3066 uses kernel 5.10.84 at the moment.
Can someone help me with this? Thanks :)

**Comment by tormath1** [comment]
Hi @TheKangaroo, 

The release page is mentioning 5.10.84 because it was the Kernel version at this time (15th of Dec.). Between the 15th of Dec. and today we got multiple Kernel bumps, for example on version 3066: https://github.com/flatcar-linux/coreos-overlay/commits/flatcar-3066/sys-kernel/coreos-sources: 5.10.84 -> 5.10.87 -> 5.10.89 -> ... -> 5.10.93.

According to the release planning: https://github.com/orgs/flatcar-linux/projects/5#column-17452795, releases should land this week. :)

**Comment by TheKangaroo** [comment]
Ok I see. Thank you for the explanation :)

**Comment by t-lo** [comment]
Release is tracked here: https://github.com/flatcar-linux/Flatcar/issues/604

**Comment by dongsupark** [comment]
FYI, Kernel 5.4.173 also has the same backported [fix](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=bd2aed0464ae3d6e83ce064cd91fc1a7fec48826).
- [x] https://github.com/flatcar-linux/coreos-overlay/pull/1584

**Comment by pothos** [comment]
Fixed in https://www.flatcar.org/releases/#release-3033.2.1, https://www.flatcar.org/releases/#release-3066.1.1, https://www.flatcar.org/releases/#release-3127.0.0, https://www.flatcar.org/releases/#release-2605.25.1
