### ISSUE TITLE
Release Flatcar Container Linux Alpha 3127.0.0, Beta 3066.1.1, Stable 3033.2.1, LTS 2605.25.1

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#604]
## Release Flatcar Container Linux Alpha 3127.0.0, Beta 3066.1.1, Stable 3033.2.1, LTS 2605.25.1
  
The release of Flatcar Container Linux Alpha 3127.0.0, Beta 3066.1.1, Stable 3033.2.1, LTS 2605.25.1 is planned for January 25th, 2022

### Tasks for Alpha 3127.0.0
- [x] Go / No Go tracking folder created, tracking doc added (@sayanchowdhury)
- [x] All planned changes are merged & blocker bugs are fixed (@sayanchowdhury)
- [x] Branch off main (only new major) (@sayanchowdhury)
- [x] Tag build branch (@sayanchowdhury)
- [x] Generate manifest (@sayanchowdhury)
- [x] Start Jenkins builds (@sayanchowdhury)
- ~[ ] Test status captured in test status tracker ()~
- [x] Create SDK container after Jenkins is done building the flatcar-sdk tarball; upload container to ghcr.io (@t-lo)
- [x] All tests are green (@sayachowdhury)
- [x] Archive TAP report (@tormath1)
- [x] create Go / No Go doc (@flatcar-linux/flatcar-maintainers)
- [x] Release notes / announcements added to Go/No Go doc (@flatcar-linux/flatcar-maintainers )
- [x] QA: check diff for image file list, packages, and image size (@pothos)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury)
- [x] Manifest release created on GitHub (@sayanchowdhury)
- [x] Update the SDK release metadata for new major Alpha releases with SDK builds (only new major) (@sayanchowdhury)
- [x] Images uploaded (@sayanchowdhury)
- [x] Run the `os/release` job (@sayanchowdhury)
- [x] Publish EC2 Marketplace Images (Submit for scanning) (@tormath1)
- [x] Publish EC2 Marketplace Images (Update Product) (@tormath1)
- [x] Azure offer updated & publishing started (@dongsupark)
- [x] Azure Go Live (@dongsupark)
- [x] GCP offers updated (@sayanchowdhury)
- [x] Update payload signed/published (@dongsupark)
- [x] Symlink to "current" updated (@sayanchowdhury)
- [x] Website updated (@sayanchowdhury)
- [x] Update CloudFormation templates (@sayanchowdhury)
- [x] Release package published in Nebraska @dongsupark
- [x] Send announcement to Mailing Lists, and tweet out! (@miao0miao, @ahrkrak)

---

### Tasks for Beta 3033.1.1
- [x] Go / No Go tracking folder created, tracking doc added (@sayanchowdhury)
- [x] All planned changes are merged & blocker bugs are fixed (@sayanchowdhury)
- [x] Branch off main (only new major) (@sayanchowdhury)
- [x] Tag build branch (@sayanchowdhury)
- [x] Generate manifest (@sayanchowdhury)
- [x] Start Jenkins builds (@sayanchowdhury)
- ~[ ] Test status captured in test status tracker ()~
- ~[ ] Create SDK container after Jenkins is done building the flatcar-sdk tarball; upload container to ghcr.io (@t-lo)~
- [x] All tests are green (@sayachowdhury)
- [x] Archive TAP report (@tormath1)
- [x] create Go / No Go doc (@flatcar-linux/flatcar-maintainers)
- [x] Release notes / announcements added to Go/No Go doc (@flatcar-linux/flatcar-maintainers )
- [x] QA: check diff for image file list, packages, and image size (@pothos)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury)
- [x] Manifest release created on GitHub (@sayanchowdhury)
- [x] Update the SDK release metadata for new major Alpha releases with SDK builds (only new major) (@sayanchowdhury)
- [x] Images uploaded (@sayanchowdhury)
- [x] Run the `os/release` job (@sayanchowdhury)
- [x] Publish EC2 Marketplace Images (Submit for scanning) (@tormath1)
- [x] Publish EC2 Marketplace Images (Update Product) (@tormath1)
- [x] Azure offer updated & publishing started (@dongsupark)
- [x] Azure Go Live (@dongsupark)
- [x] GCP offers updated (@sayanchowdhury)
- [x] Update payload signed/published (@dongsupark)
- [x] Symlink to "current" updated (@sayanchowdhury)
- [x] Website updated (@sayanchowdhury)
- [x] Update CloudFormation templates (@sayanchowdhury)
- [x] Release package published in Nebraska @dongsupark
- [x] Send announcement to Mailing Lists, and tweet out! (@miao0miao, @ahrkrak)

---

### Tasks for Stable 3033.2.1
- [x] Go / No Go tracking folder created, tracking doc added (@sayanchowdhury)
- [x] All planned changes are merged & blocker bugs are fixed (@sayanchowdhury)
- [x] Branch off main (only new major) (@sayanchowdhury)
- [x] Tag build branch (@sayanchowdhury)
- [x] Generate manifest (@sayanchowdhury)
- [x] Start Jenkins builds (@sayanchowdhury)
- ~[ ] Test status captured in test status tracker ()~
- ~[ ] Create SDK container after Jenkins is done building the flatcar-sdk tarball; upload container to ghcr.io (@t-lo)~
- [x] All tests are green (@sayachowdhury)
- [x] Archive TAP report (@tormath1)
- [x] create Go / No Go doc (@flatcar-linux/flatcar-maintainers)
- [x] Release notes / announcements added to Go/No Go doc (@flatcar-linux/flatcar-maintainers )
- [x] QA: check diff for image file list, packages, and image size (@pothos)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury)
- [x] Manifest release created on GitHub (@sayanchowdhury)
- [x] Update the SDK release metadata for new major Alpha releases with SDK builds (only new major) (@sayanchowdhury)
- [x] Images uploaded (@sayanchowdhury)
- [x] Run the `os/release` job (@sayanchowdhury)
- [x] Publish EC2 Marketplace Images (Submit for scanning) (@tormath1)
- [x] Publish EC2 Marketplace Images (Update Product) (@tormath1)
- [x] Azure offer updated & publishing started (@dongsupark)
- [x] Azure Go Live (@dongsupark)
- [x] GCP offers updated (@sayanchowdhury)
- [x] Update payload signed/published (@dongsupark)
- [x] Symlink to "current" updated (@sayanchowdhury)
- [x] Website updated (@sayanchowdhury)
- [x] Update CloudFormation templates (@sayanchowdhury)
- [x] Release package published in Nebraska @dongsupark
- [x] Send announcement to Mailing Lists, and tweet out! (@miao0miao, @ahrkrak)

---

### Tasks for LTS 2605.25.1
- [x] Go / No Go tracking folder created, tracking doc added (@sayanchowdhury)
- [x] All planned changes are merged & blocker bugs are fixed (@sayanchowdhury)
- [x] Branch off main (only new major) (@sayanchowdhury)
- [x] Tag build branch (@sayanchowdhury)
- [x] Generate manifest (@sayanchowdhury)
- [x] Start Jenkins builds (@sayanchowdhury)
- ~[ ] Test status captured in test status tracker ()~
- ~[ ] Create SDK container after Jenkins is done building the flatcar-sdk tarball; upload container to ghcr.io (@t-lo)~
- [x] All tests are green (@sayachowdhury)
- [x] Archive TAP report (@tormath1)
- [x] create Go / No Go doc (@flatcar-linux/flatcar-maintainers)
- [x] Release notes / announcements added to Go/No Go doc (@flatcar-linux/flatcar-maintainers )
- [x] QA: check diff for image file list, packages, and image size (@pothos)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury)
- [x] Manifest release created on GitHub (@sayanchowdhury)
- [x] Update the SDK release metadata for new major Alpha releases with SDK builds (only new major) (@sayanchowdhury)
- [x] Images uploaded (@sayanchowdhury)
- [ ] Run the `os/release` job (@sayanchowdhury)
- [x] Publish EC2 Marketplace Images (Submit for scanning) (@tormath1)
- [x] Publish EC2 Marketplace Images (Update Product) (@tormath1)
- [x] Azure offer updated & publishing started (@dongsupark)
- [x] Azure Go Live (@dongsupark)
- [ ] GCP offers updated (@sayanchowdhury)
- [x] Update payload signed/published (@dongsupark)
- [x] Symlink to "current" updated (@sayanchowdhury)
- [x] Website updated (@sayanchowdhury)
- [ ] Update CloudFormation templates (@sayanchowdhury)
- [x] Release package published in Nebraska @dongsupark
- [x] Send announcement to Mailing Lists, and tweet out! (@miao0miao, @ahrkrak)

**Comment by t-lo** [comment]
SDK container for 3127 is built and currently uploading to ghcr.io.

**Comment by tormath1** [comment]
Do we need to split the tasklist for each channel ? IMHO it's harder to maintain / follow :) Most of the time, release steps are common between each channel.

**Comment by sayanchowdhury** [comment]
> Do we need to split the tasklist for each channel ? IMHO it's harder to maintain / follow :) Most of the time, release steps are common between each channel.

Yes, I will try to find a better way. Sometimes, for a few channels things fail and we would need to track through this but agreed this multiple comment is tedious and not too clear

**Comment by sayanchowdhury** [comment]
Thank you all for the collaboration on the release. 🌮 🍿
