### ISSUE TITLE
Community Call 2022-02-08

### ISSUE THREAD

**Issue by miao0miao** [flatcar/Flatcar#613]
## TODO list for the meeting
  - [x] 1 week before meeting: Create Agenda PR @miao0miao (https://github.com/flatcar-linux/Flatcar/discussions/612)
  - [x] 1 week before meeting: Tweet "ask for input" @miao0miao  w/ link to agenda PR (so people can add topcis)
  - [x] Monday before meeting: Finish and merge Agenda @miao0miao 
  - [x] Monday before meeting: Tweet announcement @ahrkrak 
  - [x] 1h before meeting: announce in matrix (w/ Zoom link) @miao0miao 
  - [x] Start meeting, add recording link to agenda @miao0miao 
  - [x] conduct meeting @miao0miao 
  - [x] after meeting, add slides (PDF) to agenda @miao0miao

**Comment by miao0miao** [comment]
the meeting was conducted last evening
