### ISSUE TITLE
Release Flatcar Container Linux Alpha 3139.0.0, Beta 3066.1.2, Stable 3033.2.2

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#618]
## Release Flatcar Container Linux Alpha 3139.0.0, Beta 3066.1.2, Stable 3033.2.2
  
The release of Flatcar Container Linux Alpha 3139.0.0, Beta 3066.1.2, Stable 3033.2.2 is planned for February 7th, 2022

### Tasks
- [x] Go / No Go tracking folder created, tracking doc added (@sayanchowdhury
- [x] All planned changes are merged & blocker bugs are fixed (@sayanchowdhury)
- [x] Branch off main (only new major) (@sayanchowdhury)
- [x] Tag build branch (@sayanchowdhury)
- [x] Generate manifest (@sayanchowdhury)
- [x] Start Jenkins builds (@sayanchowdhury)
- [x] Test status captured in test status tracker (@sayanchowdhury)
- [x] Create SDK container after Jenkins is done building the flatcar-sdk tarball; upload container to ghcr.io (@t-lo)
- [x] All tests are green (@sayanchowdhury)
- [x] Archive TAP report, create Go / No Go doc (@sayanchowdhury)
- [x] Release notes / announcements added to Go/No Go doc (@sayanchowdhury)
- [x] QA: check diff for image file list, packages, and image size (@sayanchowdhury)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury)
- [x] Manifest release created on GitHub (@sayanchowdhury)
- [x] Update the SDK release metadata for new major Alpha releases with SDK builds (only new major) (@sayanchowdhury)
- [x] Images uploaded (@sayanchowdhury)
- [x] Run the `os/release` job (@sayanchowdhury)
- [x] Publish EC2 Marketplace Images (Submit for scanning) (@tormath1 )
- [x] Publish EC2 Marketplace Images (Update Product) (@tormath1 )
- [x] Azure offer updated & publishing started (@sayanchowdhury)
- [x] Azure Go Live (@sayanchowdhury)
- [x] GCP offers updated (@sayanchowdhury)
- [x] Update payload signed/published (@dongsupark)
- [x] Symlink to "current" updated (@sayanchowdhury)
- [x] Website updated (@sayanchowdhury)
- [x] Update CloudFormation templates (@sayanchowdhury)
- [x] Release package published in Nebraska (@dongsupark )
- [x] Send announcement to Mailing Lists, and tweet out! (@miao0miao, @ahrkrak)

**Comment by sayanchowdhury** [comment]
Marking this release as complete
