### ISSUE TITLE
[Tracking] incompatibilities between Nebraska 2.6 and Flatcar release process

### ISSUE THREAD

**Issue by dongsupark** [flatcar/Flatcar#622]
During the Flatcar releases in this week, a number of incompatibility issues were found between Nebraska [2.6.0](https://github.com/kinvolk/nebraska/releases/tag/2.6.0) and the Flatcar release process, especially when uploading [update payloads](https://github.com/flatcar-linux/flatcar-build-scripts/blob/master/upload_package). For now Nebraska has been reverted to 2.5.1 in the production servers of Update Service, so it works again. However, the issues will appear again when it would be updated to 2.6. So let's track the discovered issues.

**Issues for Nebraska both pre-2.6 and 2.6**

- [x] POST fails with `header Content-Type has unexpected value application/x-www-form-urlencoded` (https://github.com/flatcar-linux/flatcar-build-scripts/pull/95)

**Issues for only Nebraska 2.6**

- [x] Authentication with bearer token does not work (https://github.com/kinvolk/nebraska/pull/569)
- [x] GET and its [json parsing code](https://github.com/flatcar-linux/flatcar-build-scripts/blob/62f6b6a1e8cccf8f0ffb1e9b7e0d1a3465fa3bf4/upload_package#L56) fails with `version` field missing. (https://github.com/flatcar-linux/flatcar-build-scripts/pull/96)
- [x] POST for [uploading](https://github.com/flatcar-linux/flatcar-build-scripts/blob/62f6b6a1e8cccf8f0ffb1e9b7e0d1a3465fa3bf4/upload_package#L65) fails with `Error at /channels_blacklist: property channels_blacklist is missing`. (https://github.com/flatcar-linux/flatcar-build-scripts/pull/96)
- [x] Nebraska UI shows only 5 latest versions when selecting versions for each channel. (https://github.com/kinvolk/nebraska/issues/570) (https://github.com/kinvolk/nebraska/pull/569) (https://github.com/kinvolk/nebraska/pull/581)
- [x] issue in the host-flatcar-packages option (https://github.com/kinvolk/nebraska/issues/575)

**Comment by dongsupark** [comment]
All PRs were merged, and upload_package was tested against a staging server with Nebraska 2.6.
Everything looks good.

**Comment by jepio** [comment]
We found another issue reported by a user in the host-flatcar-packages option (works in 2.5.1):
- [x] https://github.com/kinvolk/nebraska/issues/575

**Comment by dongsupark** [comment]
Nebraska [2.7.0](https://github.com/kinvolk/nebraska/releases/tag/2.7.0) was released with bug fixes, and the public server was also updated.
