### ISSUE TITLE
[ROADMAP] Automate and Revamp Flatcar Build Release Pipeline

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#632]
### Foundational

- [ ] Build the foundation Flatcar Release tool (or Jenkins job for publishing, see [here](https://github.com/flatcar-linux/Flatcar/issues/650#issuecomment-1164458837)) to handle the release.

### Pre-Builds

- [ ] Build a Release Planning SOP
- [ ] Automate the triggering of the Jenkins Release Builds
- [ ] Integrate a step to automate the triggering of the release tool - https://github.com/flatcar-linux/Flatcar/issues/650
- [x] Remaining tasks for new pipeline: https://github.com/flatcar-linux/Flatcar/issues/786 and https://github.com/flatcar-linux/Flatcar/issues/623 https://github.com/flatcar-linux/Flatcar/issues/844

### Post-Builds <-> Pre Go/No-Go

- [x] Implement auto-restarts of Flaky tests to better utilize time
- [ ] Automate building of the Go/No-Go document and integrate it into the release tool - https://github.com/flatcar-linux/Flatcar/issues/650
	* [x] Integrate the changelog-aggregator
	* Integrate the CVE Generation tool
- [x] Build a Jenkins pipeline to store the meta-information of every manifest, size, content, and package difference.

### Post Go/No-Go
- [x] Automate the publishing to Azure Marketplace - https://github.com/flatcar-linux/Flatcar/issues/633
- [x] Automate the publishing to AWS Marketplace
- [ ] Automate the publishing to GCP Marketplace
- [ ] Integrate the release steps into the release tool
	* Interact with the Origin
	* Update SDK
	* CF templates
	* Update Website
- [ ] Strech goal: Automate Signing Updates (using a vault?) and integrate into the Release pipeline

### Community

- [x] Create a CI pipeline for when a PR is created in the Github repo(s): tracking this in https://github.com/flatcar/Flatcar/issues/790.

**Comment by t-lo** [comment]
I think this roadmap item overlaps with the above: https://github.com/flatcar-linux/Flatcar/issues/442
