### ISSUE TITLE
Community Call 2022-03-08

### ISSUE THREAD

**Issue by miao0miao** [flatcar/Flatcar#641]
## TODO list for the meeting
  - [x]  1 week before meeting: Create Agenda PR @miao0miao  (https://github.com/flatcar-linux/Flatcar/discussions/640)
  - [x] ~~1 week before meeting: Tweet "ask for input" @ahrkrak w/ link to agenda PR (so people can add topcis)~~
  - [x] Monday before meeting: Finish and merge Agenda @jepio 
  - [x] ~~Monday before meeting: Tweet announcement @ahrkrak~~
  - [x] 1h before meeting: announce in matrix (w/ Zoom link) @jepio  
  - [x] Start meeting, add recording link to agenda @jepio @t-lo  
  - [x] conduct meeting @flatcar-linux/flatcar-maintainers  
  - [x] ~~after meeting, add slides (PDF) to agenda @jepio~~
