### ISSUE TITLE
Documentation writing day 2022-03-04

### ISSUE THREAD

**Issue by miao0miao** [flatcar/Flatcar#642]
The goal of this event is to go through the Flatcar [documentation](https://www.flatcar.org/docs/latest/) and make sure it is up to date and add missing documentation.    
## TODO list for the meeting
  - [ ] Monday before meeting: Tweet announcement @miao0miao @ahrkrak 
  - [ ] add event to the Flatcar Community [Calendar]
  - [ ] 1h before meeting: announce in matrix  @t-lo 
  - [ ]  add the YouTube link to the event
  - [ ]  Thursday before meeting: Tweet announcement @miao0miao @ahrkrak 
  - [ ] Start meeting, add recording @t-lo 
  - [ ] conduct the event @flatcar-linux/flatcar-maintainers

**Comment by tormath1** [comment]
The event has been done. It has been mentioned in this community call: https://github.com/flatcar-linux/Flatcar/discussions/640 and YT video is available: https://www.youtube.com/watch?v=O9fnK9CvwjI
