### ISSUE TITLE
[roadmap] ensure Flatcar's quality across the releases

### ISSUE THREAD

**Issue by tormath1** [flatcar/Flatcar#652]
The goal of this issue is to track the various steps involved to ensure Flatcar's quality across the releases:

## Documentation side
- [ ] https://github.com/flatcar-linux/Flatcar/issues/651
- [ ] https://github.com/flatcar-linux/Flatcar/issues/653

## Development side
- [ ] https://github.com/flatcar-linux/Flatcar/issues/654
- [ ] https://github.com/flatcar-linux/Flatcar/issues/655

**Comment by t-lo** [comment]
There's overlap with this roadmap item: https://github.com/flatcar-linux/Flatcar/issues/442

**Comment by pothos** [comment]
@tormath1 With too many roadmap issues in the "In Progress" column, can I move this to "Accepted / Queued"?
The test execution time was tackled but of course improving the tests is always an ongoing topic, not sure if it's a current important focus, thought, that we actively work on.

**Comment by tormath1** [comment]
@pothos I'm fine to move this to the "Accepted / Queued" - as you said, it's always an on-going topic.
