### ISSUE TITLE
Release Flatcar Container Linux Alpha 3165.0.0, Beta 3139.1.0, Stable 3033.2.3, LTS 2605.26.1

### ISSUE THREAD

**Issue by dongsupark** [flatcar/Flatcar#662]
## Release Flatcar Container Linux Alpha 3165.0.0, Beta 3139.1.0, Stable 3033.2.3, LTS 2605.26.1
  
The release of Flatcar Container Linux Alpha 3165.0.0, Beta 3139.1.0, Stable 3033.2.3, LTS 2605.26.1 is planned for Mar. 7th, 2022. 

### Tasks
- [x] Go / No Go tracking folder created, tracking doc added (@dongsupark)
- [x] All planned changes are merged & blocker bugs are fixed (@dongsupark)
- [x] Branch off main (only new major) (@dongsupark)
- [x] Tag build branch (@dongsupark)
- [x] Generate manifest (@dongsupark)
- [x] Start Jenkins builds (@dongsupark)
- [x] Test status captured in test status tracker (@dongsupark)
- [x] Create SDK container after Jenkins is done building the flatcar-sdk tarball; upload container to ghcr.io (@t-lo)
- [x] All tests are green (@dongsupark)
- [x] Archive TAP report, create Go / No Go doc (@dongsupark) - no TAP report, due to missing data caused by Jenkins cleanup issues
- [x] Release notes / announcements added to Go/No Go doc (@dongsupark)
-  QA: check diff for image file list, packages, and image size (@dongsupark) - no diff for image file list, due to missing data caused by Jenkins cleanup issues
- [x] Matrix Go/No Go meeting (inc. release notes review) (@dongsupark)
- [x] Manifest release created on GitHub (@dongsupark)
- [x] Update the SDK release metadata for new major Alpha releases with SDK builds (only new major) (@dongsupark)
- [x] Images uploaded (@dongsupark)
- [x] Run the `os/release` job (@dongsupark)
- [x] Publish EC2 Marketplace Images (@tormath1)
- [x] Azure offer updated & publishing started (@sayanchowdhury)
- [x] Azure Go Live (@sayanchowdhury)
- [x] GCP offers updated (@sayanchowdhury)
- [x] Update payload signed/published (@dongsupark)
- [x] Symlink to "current" updated (@dongsupark)
- [x] Website updated (@dongsupark)
- [x] Update CloudFormation templates (@dongsupark)
- [x] Release package published in Nebraska (@dongsupark)
- [x] Send announcement to Mailing Lists, and tweet out! (@pothos, @ahrkrak)

**Comment by sayanchowdhury** [comment]
To update on the Azure, and GCP offers:
- Azure has some changes in drafts which needs attention is blocking the publishing
- GCP Partner Portal is not accepting any changes and request for [transition to Producer Portal](https://cloud.google.com/marketplace/docs/partners/portal-migration) which also being looked into

**Comment by dongsupark** [comment]
Done. GCP was published last week.
