### ISSUE TITLE
Release Team Call - 22nd March 2022

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#679]
## TODO list for the meeting
  - [x] 1 week before meeting: Create Agenda on [Github Discussion](https://github.com/flatcar-linux/Flatcar/discussions/678) board @sayanchowdhury
  - [x] 1 week before meeting: Tweet "Invitation to Release Team Call w/ link to agenda discussion" (so people can add topics)
  - [x] Monday before meeting: Finish and merge Agenda @dongsupark @pothos 
  - [x] Monday before meeting: Tweet announcement @ahrkrak
  - [x] 1h before meeting: announce in matrix (w/ Zoom link) @dongsupark @pothos
  - [x] Start meeting, add recording link to agenda @t-lo  
  - [x] conduct meeting @tormath1 @dongsupark @pothos

**Comment by tormath1** [comment]
Thanks everyone, the recording is available here: https://www.youtube.com/watch?v=YqgxhzP8UV4. Let's close this issue.
