### ISSUE TITLE
Release Flatcar Container Linux Alpha 3185.0.0, Beta 3139.1.1, Stable 3033.2.4

### ISSUE THREAD

**Issue by dongsupark** [flatcar/Flatcar#687]
## Release Flatcar Container Linux Alpha 3185.0.0, Beta 3139.1.1, Stable 3033.2.4
  
The release of Flatcar Container Linux Alpha 3185.0.0, Beta 3139.1.1, Stable 3033.2.4 is planned for Mar. 23rd, 2022. 

### Tasks
- [x] Go / No Go tracking folder created, tracking doc added (@dongsupark)
- [x] All planned changes are merged & blocker bugs are fixed (@dongsupark)
- [x] Branch off main (only new major) (@dongsupark)
- [x] Tag build branch (@dongsupark)
- [x] Generate manifest (@dongsupark)
- [x] Start Jenkins builds (@dongsupark)
- [x] Test status captured in test status tracker (@dongsupark)
- [x] Create SDK container after Jenkins is done building the flatcar-sdk tarball; upload container to ghcr.io (@t-lo)
- [x] All tests are green (@dongsupark)
- [x] Archive TAP report, create [Go / No Go doc](https://hackmd.io/GKLk-FkgQ1enlnakPZPEUw) (@dongsupark)
  - TAP reports for Alpha missing due to Jenkins issue 
- [x] Release notes / announcements added to Go/No Go doc (@dongsupark)
- [x] QA: check diff for image file list, packages, and image size (@pothos)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@dongsupark)
- [x] Manifest release created on GitHub (@dongsupark)
- [x] Update the SDK release metadata for new major Alpha releases with SDK builds (only new major) (@dongsupark)
- [x] Images uploaded (@dongsupark)
- [x] Run the `os/release` job (@dongsupark)
- [x] Publish EC2 Marketplace Images (@tormath1)
- [x] Azure offer updated & publishing started (@tormath1)
- [x] Azure Go Live (@tormath1)
- [x] GCP offers updated (@dongsupark)
- [x] Update payload signed/uploaded (@dongsupark)
- [x] Symlink to "current" updated (@dongsupark)
- [x] Website updated (@dongsupark)
- [x] Update CloudFormation templates (@dongsupark)
- [x] Release package published in Nebraska (@dongsupark)
- [x] Send announcement to Mailing Lists, and tweet out! (@miao0miao, @ahrkrak)

**Comment by pothos** [comment]
I've reviewed the image contents changes and size. Created two follow-up issues https://github.com/flatcar-linux/Flatcar/issues/688 and https://github.com/flatcar-linux/Flatcar/issues/689

**Comment by dongsupark** [comment]
Done already a long time ago.
