### ISSUE TITLE
Community Call 2022-04-12

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#703]
## TODO list for the meeting
  - [x] 1 week before meeting: Create Agenda (@t-lo ) - https://github.com/flatcar-linux/Flatcar/discussions/704
  - [x] 1 week before meeting: Tweet "ask for input" (@t-lo) w/ link to agenda PR (so people can add topcis)
  - [x] Monday before meeting: Finish Agenda @t-lo 
  - [x] Monday before meeting: Tweet announcement @[owner]
  - [x] 1h before meeting: announce in matrix (w/ Zoom link) @t-lo 
  - [x] Start meeting, add recording link to agenda @t-lo 
  - [x] conduct meeting @t-lo

**Comment by tormath1** [comment]
Community call has been done - recording is available here: https://www.youtube.com/watch?v=dYGhoEssdoc. Thanks all !
