### ISSUE TITLE
Release Flatcar Container Linux 3033.3.0 for LTS-2022

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#724]
## Release Flatcar Container Linux lts-3033.3.0
  
The release of Flatcar Container Linux 3033.3.0 is planned for May 5th/6th, 2022. 

### Tasks
- [x] Go / No Go tracking folder created, tracking doc added: https://hackmd.io/0o9ilUkXSbCLZdehyaKqVA?view
- [x] All planned changes are merged & blocker bugs are fixed (@pothos)
- [x] Tag build branch (@pothos)
- [x] Generate manifest (@pothos)
- [x] Start Jenkins builds (@pothos)
- [x] Test status captured in test status tracker
- [x] All tests are green (@pothos)
- [x] Archive TAP report, create Go / No Go doc (TAP report includes unrelated failures)
- [x] Release notes / announcements added to Go/No Go doc (@pothos)
- [x] QA: check diff for image file list, packages, and image size (@pothos) [found that there was no networkd.conf drop-in file for disabling foreign route management → rebuilding]
- [x] Matrix Go/No Go meeting (inc. release notes review) (@pothos)
- [x] Manifest release created on GitHub (@pothos)
- [x] Images uploaded (@pothos)
- [x] Run the `os/release` job (@pothos)
- [ ] Publish EC2 Marketplace Images (@sayanchowdhury)
- [x] Azure offer updated & publishing started (@dongsupark)
- [x] Azure Go Live (@dongsupark)
- [ ] GCP offers updated (@sayanchowdhury)
- [x] Update payload signed/published (@pothos)
- [x] Symlink to "current" updated (@pothos)
- [x] Website updated (@pothos)
- [x] Update CloudFormation templates (@pothos)
- [x] Release package published in Nebraska (@pothos)
- [x] Send announcement to Mailing Lists, and tweet out! (@pothos, @ahrkrak)

**Comment by pothos** [comment]
Restarted tests:

- Packet arm64: because of timeout
- Packet amd64:  `coreos.auth.verify cl.ignition.v2.xfsroot cl.update.reboot` because auf timeout/kernel warning `arch/x86/kernel/apic/ipi.c:68 native_smp_send_reschedule+0x34/0x40`
- AWS arm64: `cl.cloudinit.basic kubeadm.v1.23.4.flannel.base` because of timeout

(arm64 qemu_uefi update test can't run because there was no previous LTS arm64 release)

**Comment by pothos** [comment]
The TAP summary has wrong entries but all tests have passed except the Packet arm64 test which is still running (takes ~10 hours).

**Comment by pothos** [comment]
Found an issue when doing `FILE=flatcar_production_image_contents.txt FILESONLY=1 CUTKERNEL=1   CHANNEL_A=stable CHANNEL_B=lts ~/kinvolk/flatcar-build-scripts/package-diff  3033.2.4  3033.3.0`, rebuilding now and will check that the missing networkd.conf.d drop-in file shows up then. Edit: checked and it looks good

After rebuilding (see below) I had to restart a few tests again due to some timeouts.

**Comment by pothos** [comment]
Sayan posted the last state for the GCP offer update in Matrix:

> I've created the Flatcar LTS Product on the GCP, and uploaded a deployment package based on Flatcar LTS 3033.3.0. It's running the validating tests. Let's see how it goes

**Comment by pothos** [comment]
@sayanchowdhury Can we close this?
