### ISSUE TITLE
Community Call on Tuesday, 10nd of May 2022 17:30 CET / 11:30am EDT / 8:30am PDT

### ISSUE THREAD

**Issue by miao0miao** [flatcar/Flatcar#727]
## TODO list for the meeting
  - [x] 1 week before meeting: Create Agenda PR @miao0miao 
  - [ ] 1 week before meeting: Tweet "ask for input" @miao0miao  w/ link to agenda PR (so people can add topcis)
  - [ ] Monday before meeting: Finish and merge Agenda @miao0miao 
  - [ ] Monday before meeting: Tweet announcement @miao0miao 
  - [ ] 1h before meeting: announce in matrix (w/ Zoom link) @miao0miao 
  - [ ] Start meeting, add recording link to agenda @miao0miao 
  - [ ] conduct meeting @miao0miao

**Comment by t-lo** [comment]
@pothos wanted to briefly introduce the (community) LTS-2022 release.
