### ISSUE TITLE
Release Flatcar Container Linux Alpha 3277.0.0, Beta 3227.1.1, Stable 3139.2.3, LTS-2021 2605.29.1 LTS-2022 3033.3.2

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#784]
## Release Flatcar Container Linux Alpha 3277.0.0, Beta 3227.1.1, Stable 3139.2.3, LTS-2021 2605.29.1 LTS-2022 3033.3.2

The release of Flatcar Container Linux Alpha 3277.0.0, Beta 3227.1.1, Stable 3139.2.3, LTS-2021 2605.29.1 LTS-2022 3033.3.2 is planned for June 23rd, 2022. 

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [link](https://hackmd.io/puOQlpP1TaSWDRYh67qPUQ?view) (@dongsupark )
- [x] All planned changes are merged & blocker bugs are fixed (@flatcar-linux/flatcar-maintainers )
- [x] Branch off main (only new major) (@sayanchowdhury )
- [x] Tag build branch (@sayanchowdhury )
- [x] Generate manifest (@sayanchowdhury )
- [x] Start Jenkins builds, post links as comment (@sayanchowdhury )
- [x] Test status captured in hackmd doc (@dongsupark )
- [x] Create SDK container after Jenkins is done building the flatcar-sdk tarball; upload container to ghcr.io (@tormath1 
- [x] All tests are green (@sayanchowdhury )
- [x] Release notes / announcements added to Go/No Go doc with `show-changes`/`show-fixed-kernel-cves.py` (@dongsupark )
- [x] QA: check diff for image file list, packages, and image size in the image job output (@sayanchowdhury )
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury )
- [x] Manifest release created on GitHub (@sayanchowdhury )
- [x] Update the SDK release metadata for new major Alpha releases with SDK builds (only new major) (@sayanchowdhury )
- [x] Images uploaded with `copy-to-origin.sh` (@sayanchowdhury )
- [x] Run the `os/release` job (@sayanchowdhury )
- [x] Publish EC2 Marketplace Images (@tormath1  )
- [x] Azure offer updated & publishing started (@pothos )
- [x] Azure Go Live (@pothos )
- [x] GCP offers updated (@sayanchowdhury )
- [x] Update payload signed/uploaded (@dongsupark )
- [x] Symlink to "current" updated with `set-symlink.sh` (@sayanchowdhury )
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@pothos )
- [x] Update CloudFormation templates (@pothos )
- [x] Release package published in Nebraska (@dongsupark )
- [x] Send announcement to Mailing Lists (@pothos)
- [x] Send Tweet out (@miao0miao, @ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel

**Comment by tormath1** [comment]
EC2 marketplaces images sent to verification except for:
* LTS-2022 3033.3.2 (ARM64): need to create the offer
* LTS-2021 2605.29.1 (AMD64) because we can't upload two versions on the same offer at the same time - so it should be good my tomorrow.

EDIT:
* LTS-2022 3033.3.2 (ARM64): offer should be available the next week
* LTS-2021 2605.29.1 (AMD64): is failing to be scanned atm

**Comment by sayanchowdhury** [comment]
GCP is published. Closing the release.
