### ISSUE TITLE
Release Flatcar Container Linux Alpha 3305.0.0 Beta 3277.1.0 Stable 3227.2.0 LTS-2022 3033.3.3

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#803]
## Release Flatcar Container Linux Alpha 3305.0.0 Beta 3277.1.0 Stable 3227.2.0 LTS-2022 3033.3.3

The release of Flatcar Container Linux Alpha 3305.0.0 Beta 3277.1.0 Stable 3227.2.0 LTS-2022 3033.3.3 is planned for July 21st, 2022. 

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [link](TODO) (@dongsupark )
- [x] All planned changes are merged & blocker bugs are fixed (@dongsupark )
- [x] Branch off main (only new major) (@sayanchowdhury )
- [x] Tag build branch (@sayanchowdhury )
- [x] Generate manifest (@sayanchowdhury )
- [x] Test status captured in hackmd doc (@dongsupark )
- [x] Create SDK container after Jenkins is done building the flatcar-sdk tarball; upload container to ghcr.io (@pothos)
- [x] All tests are green (@flatcar-linux/flatcar-maintainers )
- [x] Release notes / announcements added to Go/No Go doc with `show-changes`/`show-fixed-kernel-cves.py` (@dongsupark / @sayanchowdhury )
- [x] QA: check diff for image file list, packages, and image size in the image job output (@dongsupark )
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury )
- [x] Manifest release created on GitHub (@sayanchowdhury)
- [x] Update the SDK release metadata for new major Alpha releases with SDK builds (only new major) (@sayanchowdhury)
- [x] Images uploaded with `copy-to-origin.sh` (@sayanchowdhury)
- [x] Run the `os/release` job (@sayanchowdhury)
- [ ] Publish EC2 Marketplace Images (@sayanchowdhury)
- [x] Azure offer updated & publishing started (@sayanchowdhury)
- [x] Azure Go Live (@sayanchowdhury)
- [ ] GCP offers updated (@sayanchowdhury)
- [x] Update payload signed/published (@dongsupark )
- [x] Symlink to "current" updated with `set-symlink.sh` (@sayanchowdhury)
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@sayanchowdhury)
- [x] Update CloudFormation templates (@sayanchowdhury)
- [x] Release package published in Nebraska (@dongsupark )
- [x] Send announcement to Mailing Lists (@pothos )
- [x] Send Tweet out (@miao0miao, @blixtra)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel  (@dongsupark)

**Comment by dghubble** [comment]
The latest Flatcar Linux stable release on Azure seems to be 3139.2.3, should 3227.2.0 be available according to this checklist?

```
az vm image list --all -p kinvolk -f flatcar -s stable | grep flatcar-container-linux-free
...
  "urn": "kinvolk:flatcar-container-linux-free:stable:3139.2.2",
  "offer": "flatcar-container-linux-free",
  "urn": "kinvolk:flatcar-container-linux-free:stable:3139.2.3",
  "offer": "flatcar-container-linux-free",
```

**Comment by dongsupark** [comment]
@dghubble Thanks for asking.
Recently we released new bugfix releases including Stable 3227.2.1.
Can you please try to use the new version?

```
az vm image list --all -p kinvolk -f flatcar -s stable | grep flatcar-container-linux-free
...
  "urn": "kinvolk:flatcar-container-linux-free:stable:3139.2.3",
  "offer": "flatcar-container-linux-free",
  "urn": "kinvolk:flatcar-container-linux-free:stable:3227.2.1",
  "offer": "flatcar-container-linux-free",
```

**Comment by sfotony** [comment]
@dongsupark I have a dependency on kernel 5.15.55.  Can you confirm that `3227.2.0` has been removed from Azure?  It appears to still be available on AWS.

**Comment by sayanchowdhury** [comment]
@sfotony We provide a more recent kernel [5.15.58](https://lwn.net/Articles/902917)  in `3227.2.1`. We are also in between a release at the moment which would provide a more recent kernel. Would it be possible for you to upgrade to those versions?

**Comment by sayanchowdhury** [comment]
I'll close this issue, but we can keep the conversations ongoing.

**Comment by sfotony** [comment]
Thanks @sayanchowdhury !  My use-case is a piece of third-party-supplied software with strict kernel version requirements.  @t-lo gave me the info I needed in Kubernetes Slack today as well, and I'm bringing those options back to my team.  Thanks for the response, and have a good weekend!

**Comment by sayanchowdhury** [comment]
Thanks @sfotony
