### ISSUE TITLE
Regressions in 3227.2.0 release - tracking parent issue 

### ISSUE THREAD

**Issue by miao0miao** [flatcar/Flatcar#810]
We created this issue to group all related issues/discussions to the regressions observed in 3227.2.0, we are working on a patch release currently and will keep posting here for updates. 

Related issues:
- [x] https://github.com/flatcar-linux/Flatcar/issues/804
- [x] https://github.com/flatcar-linux/Flatcar/issues/808 (PR: https://github.com/flatcar-linux/coreos-overlay/pull/2061)
- [x] https://github.com/flatcar-linux/Flatcar/issues/809 (PR: https://github.com/flatcar-linux/scripts/pull/391)
- [x] https://github.com/flatcar-linux/Flatcar/issues/812 (PR: https://github.com/flatcar-linux/coreos-overlay/pull/2060)
- [x] https://github.com/flatcar-linux/Flatcar/issues/817 (PR: https://github.com/flatcar-linux/init/pull/76)
- [x] fix tmpfile entry for resolv.conf link (PR: https://github.com/flatcar-linux/coreos-overlay/pull/2057, discussion: https://kubernetes.slack.com/archives/C03GQ8B5XNJ/p1658762999205499)

The release is tracked under column 2022-08-01:
https://github.com/orgs/flatcar-linux/projects/7/views/8

- remaining issues in systemd-networkd:
  - [ ] https://github.com/flatcar-linux/Flatcar/issues/807
  - [ ] https://groups.google.com/g/flatcar-linux-user/c/44jLwvlogqQ

**Comment by dongsupark** [comment]
Updated the title and the description, as they are not only DHCP issues.

**Comment by dongsupark** [comment]
Updated the description, as the recent releases fixed most issues.
Only systemd-networkd issues are in progress.

**Comment by pothos** [comment]
We also have https://github.com/flatcar-linux/Flatcar/issues/685 still open as regression from an earlier release

**Comment by tormath1** [comment]
I think we can close this for now as #685 can live on its own (and should be soon fixed).
