### ISSUE TITLE
Release Flatcar Container Linux Alpha 3305.0.1 Beta 3277.1.1 Stable 3227.2.1 LTS-2022 3033.3.4 LTS-2021 2605.30.1

### ISSUE THREAD

**Issue by dongsupark** [flatcar/Flatcar#822]
## Release Flatcar Container Linux Alpha 3305.0.1 Beta 3277.1.1 Stable 3227.2.1 LTS-2022 3033.3.4 LTS-2021 2605.30.1

The release of Flatcar Container Linux Alpha 3305.0.1 Beta 3277.1.1 Stable 3227.2.1 LTS-2022 3033.3.4 LTS-2021 2605.30.1 is planned for August 4th, 2022. 

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [link](https://hackmd.io/faL_eM0fS9a8XpThZgmifQ?view) (@dongsupark )
- [x] All planned changes are merged & blocker bugs are fixed (@dongsupark )
-  ~~Branch off main (only new major)~~ (not needed)
- [x] Tag build branch (@dongsupark )
- [x] Generate manifest (@dongsupark )
- [x] Test status captured in hackmd doc (@dongsupark )
-  ~~Create SDK container after Jenkins is done building the flatcar-sdk tarball; upload container to ghcr.io~~ (not needed)
- [x] All tests are green (@flatcar-linux/flatcar-maintainers )
- [x] Release notes / announcements added to Go/No Go doc with `show-changes`/`show-fixed-kernel-cves.py` (@dongsupark / @sayanchowdhury )
- [x] QA: check diff for image file list, packages, and image size in the image job output (@sayanchowdhury)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@dongsupark )
- [x] Manifest release created on GitHub (@dongsupark)
-  ~~Update the SDK release metadata for new major Alpha releases with SDK builds (only new major)~~ (not needed)
- [x] Images uploaded with `copy-to-origin.sh` (@dongsupark)
- [x] Run the `os/release` job (@dongsupark)
- [x] Publish EC2 Marketplace Images (@tormath1)
- [x] Azure offer updated & publishing started (@sayanchowdhury)
- [x] Azure Go Live (@sayanchowdhury)
- [ ] GCP offers updated (@sayanchowdhury)
- [x] Update payload signed/uploaded (@dongsupark )
- [x] Symlink to "current" updated with `set-symlink.sh` (@dongsupark)
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@dongsupark)
- [x] Update CloudFormation templates (@dongsupark)
- [x] Release package published in Nebraska (@dongsupark )
- [x] Send announcement to Mailing Lists (@jepio)
- [x] Send Tweet out (@ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel  (@dongsupark)

**Comment by sayanchowdhury** [comment]
Marking this issue as done!
