### ISSUE TITLE
Release Flatcar Container Linux Alpha 3346.0.0 Beta 3277.1.2 Stable 3227.2.2 LTS-2022 3033.3.5 LTS-2021 2605.31.1

### ISSUE THREAD

**Issue by dongsupark** [flatcar/Flatcar#839]
## Release Flatcar Container Linux Alpha 3346.0.0 Beta 3277.1.2 Stable 3227.2.2 LTS-2022 3033.3.5 LTS-2021 2605.31.1

The release of Flatcar Container Linux Alpha 3346.0.0 Beta 3277.1.2 Stable 3227.2.2 LTS-2022 3033.3.5 LTS-2021 2605.31.1 is planned for September 1st, 2022. 

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [link](https://hackmd.io/ssyetrlOSaegYpBVVtlieQ?view) (@dongsupark / @sayanchowdhury )
- [x] All planned changes are merged & blocker bugs are fixed (@dongsupark )
- [x] Branch off main (only new major) (@dongsupark )
- [x] Tag build branch (@dongsupark )
- [x] Generate manifest (@dongsupark )
- [x] Test status captured in hackmd doc (@dongsupark )
- [x] Create SDK container after Jenkins is done building the flatcar-sdk tarball; upload container to ghcr.io ()
- [x] All tests are green (@flatcar-linux/flatcar-maintainers )
- [x] Release notes / announcements added to Go/No Go doc with `show-changes`/`show-fixed-kernel-cves.py` (@dongsupark / @sayanchowdhury )
- [ ] QA: check diff for image file list, packages, and image size in the image job output ()
- [x] Matrix Go/No Go meeting (inc. release notes review) (@dongsupark )
- [x] Manifest release created on GitHub (@dongsupark)
- [x] Update the SDK release metadata for new major Alpha releases with SDK builds (only new major) (@dongsupark)
- [x] Images uploaded with `copy-to-origin.sh` (@dongsupark)
- [x] Run the `os/release` job (@dongsupark)
- [x] Publish EC2 Marketplace Images (@tormath1 )
- [x] Azure offer updated & publishing started (@sayanchowdhury)
- [x] Azure Go Live (@sayanchowdhury)
- [x] GCP offers updated (@sayanchowdhury)
- [x] Update payload signed/uploaded (@dongsupark )
- [x] Symlink to "current" updated with `set-symlink.sh` (@dongsupark)
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@dongsupark)
- [x] Update CloudFormation templates (@dongsupark)
- [x] Release package published in Nebraska (@dongsupark )
- [x] Send announcement to Mailing Lists ()
- [x] Send Tweet out (@ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel (@t-lo )

**Comment by dongsupark** [comment]
FYI, `ami-02ea825969d1f499b` for Stable arm64 was set to private due to the issue https://github.com/flatcar-linux/Flatcar/issues/840.

**Comment by t-lo** [comment]
Azure marketplace offers `flatcar-container-linux-free` and `flatcar_pro` are published; `flatcar-container-linux` is still in Certification.

**Comment by sayanchowdhury** [comment]
@dongsupark  Can we close this issue?

**Comment by dongsupark** [comment]
Yeah, we still do not know what was going on with the corrupted AMI.
However, as we now run CI without vmdk, not an issue any more.
Let's close this issue.
