### ISSUE TITLE
Release Flatcar Container Linux Alpha 3374.0.0 Beta 3346.1.0

### ISSUE THREAD

**Issue by dongsupark** [flatcar/Flatcar#860]
## Release Flatcar Container Linux Alpha 3374.0.0 Beta 3346.1.0
  
The release of Flatcar Container Linux Alpha 3374.0.0 Beta 3346.1.0 is planned for September 29th, 2022.. 

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [link](https://hackmd.io/NuLz3rKZQl2B44jbZrSaRw?view) (@dongsupark)
- [x] All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems (@dongsupark)
- [x] Branch off main (only new major) (@dongsupark)
- [x] Tag build branch (@dongsupark)
- [x] Start Jenkins builds, post links as comment (@dongsupark)
- [x] Test status captured in hackmd doc (@pothos)
- [x] All tests are green (@tormath1)
- [x] Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None` (@dongsupark)
- [x] QA: check diff for image file list, packages, and image size in the image job output (@pothos)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@pothos)
- [x] Update payload signed/uploaded (@pothos)
- [x] `scripts` release created on GitHub (@pothos )
- [x] Release job `container/release` ran (@pothos )
- [x] Images uploaded with `copy-to-origin.sh` (@pothos )
- [x] Azure offer updated & publishing started (@pothos )
- [x] Azure Go Live (@tormath1)
- [ ] GCP offers updated (@tormath1)
- [x] Symlink to "current" updated with `set-symlink.sh` (@pothos )
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@pothos )
- [x] Release package published in Nebraska (@pothos )
- [x] Send announcement to Mailing Lists (@pothos )
- [x] Send Tweet out (@miao0miao, @ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel (@pothos )

**Comment by sayanchowdhury** [comment]
This release is completed. Closing the issue.
