### ISSUE TITLE
Release Flatcar Container Linux Stable 3227.2.3 LTS-2022 3033.3.6 LTS-2021 2605.32.1

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#870]
## Release Flatcar Container Linux Stable 3227.2.3 LTS-2022 3033.3.6 LTS-2021 2605.32.1
  
The release of Flatcar Container Linux Stable 3227.2.3 LTS-2022 3033.3.6 LTS-2021 2605.32.1 is planned for Oct 13 2022. 

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [link](https://hackmd.io/SzVBsJTeS--cySnQJ9i85w) (@sayanchowdhury )
- [x] All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems (@sayanchowdhury )
- [x] Tag build branch (@pothos)
- [x] Start Jenkins builds, post links as comment (@pothos)
- [x] Test status captured in hackmd doc (@sayanchowdhury )
- [x] All tests are green (@sayanchowdhury )
- [x] Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None` (@sayanchowdhury )
- [x] QA: check diff for image file list, packages, and image size in the image job output (@sayanchowdhury )
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury )
- [x] Update payload signed/published (@dongsupark )
- [x] `scripts` release created on GitHub (@sayanchowdhury )
- [x] Release job `container/release` ran (@sayanchowdhury )
- [x] Images uploaded with `copy-to-origin.sh` (@sayanchowdhury)
- [x] Azure offer updated & publishing started ()
- [x] Azure Go Live ()
- [x] GCP offers updated ()
- [x] Symlink to "current" updated with `set-symlink.sh` (@sayanchowdhury )
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@sayanchowdhury )
- [x] Release package published in Nebraska (@dongsupark)
- [x] Send announcement to Mailing Lists (@miao0miao)
- [x] Send Tweet out (@ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel (@dongsupark)

**Comment by pothos** [comment]
Stable: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/516/cldsv/
LTS-2021: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/514/cldsv/
LTS-2022: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/515/cldsv/

**Comment by sayanchowdhury** [comment]
Marking as complete
