### ISSUE TITLE
Release Flatcar Container Linux Alpha 3402.0.0, Beta 3374.1.0

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#879]
## Release Flatcar Container Linux Alpha 3402.0.0, Beta 3374.1.0
  
The release of Flatcar Container Linux Alpha 3402.0.0, Beta 3374.1.0 is planned for October 24th, 2022. 

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [link](https://hackmd.io/UplvERGgREKFgV7CXGclMQ) (@sayanchowdhury )
- [x] All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems (@flatcar/flatcar-maintainers )
- [x] Branch off main (only new major) (@dongsupark )
- [x] Tag build branch (@dongsupark )
- [x] Start Jenkins builds, post links as comment (@dongsupark )
- [x] Test status captured in hackmd doc (@sayanchowdhury )
- [x] All tests are green (@sayanchowdhury, @dongsupark )
- [x] Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None` (@sayanchowdhury)
- [x] QA: check diff for image file list, packages, and image size in the image job output (@dongsupark)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury)
- [x] Update payload signed/uploaded (@dongsupark)
- [x] `scripts` release created on GitHub (@sayanchowdhury )
- [x] Release job `container/release` ran (@sayanchowdhury )
- [x] Images uploaded with `copy-to-origin.sh` (@sayanchowdhury )
- [x] Azure offer updated & publishing started (@sayanchowdhury )
- [x] Azure Go Live (@sayanchowdhury )
- [x] GCP offers deployment package uploaded (@sayanchowdhury )
- [x] GCP offers updated (@sayanchowdhury )
- [x] Symlink to "current" updated with `set-symlink.sh` (@sayanchowdhury )
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@sayanchowdhury )
- [x] Release package published in Nebraska (@dongsupark)
- [x] Send announcement to Mailing Lists (@miao0miao)
- [x] Send Tweet out (@ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel (@dongsupark)

**Comment by sayanchowdhury** [comment]
Beta 3374.1.0 - http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/608/cldsv/
Alpha 3402.0.0 - http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/610/cldsv/

hackmd doc: https://hackmd.io/UplvERGgREKFgV7CXGclMQ

**Comment by sayanchowdhury** [comment]
Marking as complete.
