### ISSUE TITLE
Release Flatcar Container Linux Stable 3227.2.4 Beta 3374.1.1 Alpha 3402.0.1

### ISSUE THREAD

**Issue by pothos** [flatcar/Flatcar#884]
## Release Flatcar Container Linux Stable 3227.2.4 Beta 3374.1.1 Alpha 3402.0.1
  
The release of Flatcar Container Linux Stable 3227.2.4 Beta 3374.1.1 Alpha 3402.0.1 is planned for Nov 1, 2022. 

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [link](https://hackmd.io/WAGW6sitQ3SayjI2sD3KOQ) (@pothos)
- [x] All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems (@pothos)
- [ ] Branch off main (only new major) (not needed)
- [x] Tag build branch (@pothos)
- [x] Start Jenkins builds, post links as comment (@pothos)
- [x] Test status captured in hackmd doc (@pothos)
- [x] All tests are green (@pothos) - only the K8s 1.22 Cilium 0.13rc0 combination didn't work but that's not on our side
- [x] Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None` (@pothos)
- [x] QA: check diff for image file list, packages, and image size in the image job output (@pothos)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@pothos)
- [x] Update payload signed/published (@pothos)
- [x] `scripts` release created on GitHub (@pothos)
- [x] Release job `container/release` ran (@pothos)
- [x] Images uploaded with `copy-to-origin.sh` (@pothos)
- [x] Azure offer updated & publishing started (@pothos)
- [x] Azure Go Live (@pothos)
- [x] GCP offers updated (@sayanchowdhury)
- [x] Symlink to "current" updated with `set-symlink.sh` (@pothos)
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@pothos)
- [x] Release package published in Nebraska (@pothos)
- [x] Send announcement to Mailing Lists (@pothos)
- [x] Send Tweet out (@miao0miao, @ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel

**Comment by pothos** [comment]
Started the builds:
Stable http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/642/cldsv/
Beta http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/643/cldsv/
Alpha http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/644/cldsv/

**Comment by sayanchowdhury** [comment]
Marking this as complete.
