### ISSUE TITLE
Release Flatcar Container Linux Alpha 3417.0.0, Beta 3402.1.0

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#893]
## Release Flatcar Container Linux Alpha 3417.0.0, Beta 3402.1.0
  
The release of Flatcar Container Linux Alpha 3416.0.0, Beta 3402.1.0 is planned for November 7th, 2022

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [link](https://hackmd.io/fQQcKNK0SMedCgC6gQ9nuA) (@sayanchowdhury)
- [x] All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems (@sayanchowdhury)
- [x] Branch off main (only new major) (@sayanchowdhury)
- [x] Tag build branch (@sayanchowdhury)
- [x] Start Jenkins builds, post links as comment (@sayanchowdhury)
- [x] Test status captured in hackmd doc (@sayanchowdhury)
- [x] All tests are green (@sayanchowdhury)
- [x] Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None` (@sayanchowdhury)
- [x] QA: check diff for image file list, packages, and image size in the image job output (@pothos)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury )
- [x] Update payload signed/uploaded (@dongsupark )
- [x] `scripts` release created on GitHub (@sayanchowdhury)
- [x] Release job `container/release` ran (@sayanchowdhury)
- [x] Images uploaded with `copy-to-origin.sh` (@sayanchowdhury)
- [x] Azure offer updated & publishing started (@sayanchowdhury)
- [x] Azure Go Live (@sayanchowdhury)
- [x] GCP offers updated (@sayanchowdhury)
- [x] Symlink to "current" updated with `set-symlink.sh` (@sayanchowdhury)
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@sayanchowdhury)
- [x] Release package published in Nebraska (@dongsupark )
- [x] Send announcement to Mailing Lists (@pothos)
- [x] Send Tweet out (@miao0miao, @ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel (@sayanchowdhury )

**Comment by sayanchowdhury** [comment]
Alpha: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/383/cldsv/
Beta: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/708/cldsv/

**Comment by sayanchowdhury** [comment]
The GCP Marketplace is finally published. Closing this issue.
