### ISSUE TITLE
Release Flatcar Container Linux Stable 3374.2.0 LTS-2022 3033.3.7

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#899]
## Release Flatcar Container Linux Stable 3374.2.0 LTS-2022 3033.3.7
  
The release of Flatcar Container Linux Stable 3374.2.0 LTS-2022 3033.3.7 is planned for November 16th, 2022. 

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [https://hackmd.io/a9O92JFuSjOeE740U5Kb7A?view](https://hackmd.io/a9O92JFuSjOeE740U5Kb7A?view) (@sayanchowdhury)
- [x] All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems (@sayanchowdhury)
- [x] Tag build branch (@sayanchowdhury)
- [x] Start Jenkins builds, post links as comment (@sayanchowdhury)
- [x] Test status captured in hackmd doc (@sayanchowdhury)
- [x] All tests are green (@sayanchowdhury)
- [x] Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None` (@sayanchowdhury)
- [x] QA: check diff for image file list, packages, and image size in the image job output (@sayanchowdhury)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury )
- [x] Update payload signed/uploaded (@dongsupark )
- [x] `scripts` release created on GitHub (@sayanchowdhury )
- [x] Release job `container/release` ran (@sayanchowdhury )
- [x] Images uploaded with `copy-to-origin.sh` (@sayanchowdhury )
- [x] Azure offer updated & publishing started (@tormath1 and @sayanchowdhury)
- [x] Azure Go Live (@tormath1 and @sayanchowdhury)
- [x] GCP offers updated (@sayanchowdhury)
- [x] Symlink to "current" updated with `set-symlink.sh` (@sayanchowdhury )
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@sayanchowdhury )
- [x] Release package published in Nebraska (@dongsupark)
- [x] Send announcement to Mailing Lists (@pothos)
- [x] Send Tweet out (@ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel (@pothos)

**Comment by tormath1** [comment]
@sayanchowdhury I can take the GCP offers now I have the access.

**Comment by sayanchowdhury** [comment]
@tormath1 I would need to test the GCP automation over the next few releases, maybe after that you can start. Azure can have helping hand, now that we have 5 offers. Can you pick two? Maybe the CoreVM offers?

**Comment by tormath1** [comment]
@sayanchowdhury CoreVM stable offers updated on both arch. Waiting for go-live now.

**Comment by tormath1** [comment]
@sayanchowdhury "Go Live" pressed for CoreVM offers on both arch.

**Comment by sayanchowdhury** [comment]
We currently publish Flatcar images through 5 Azure offers. Four of the offers are updated and live. We are facing issues with publishing the image to one of the offer with the offer id `flatcar-container-linux-free`. This offer is missing the last few releases and we are quite close on fixing the issue.
