### ISSUE TITLE
Release Flatcar Container Linux Alpha 3446.0.0, Beta 3432.1.0, Stable 3374.2.1, LTS-2022 3033.3.8

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#910]
## Release Flatcar Container Linux Alpha 3446.0.0, Beta 3432.1.0, Stable 3374.2.1, LTS-2022 3033.3.8  
The release of Flatcar Container Linux Alpha 3446.0.0, Beta 3432.1.0, Stable 3374.2.1, LTS-2022 3033.3.8 is planned for December 08th, 2022. 

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [https://hackmd.io/fWYwR1A0RCWjxuQOho9YxQ](https://hackmd.io/fWYwR1A0RCWjxuQOho9YxQ) (@sayanchowdhury )
- [x] All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems (@sayanchowdhury )
- [x] Branch off main (only new major) (@sayanchowdhury )
- [x] Tag build branch (@sayanchowdhury )
- [x] Start Jenkins builds, post links as comment (@sayanchowdhury )
- [x] Test status captured in hackmd doc (@sayanchowdhury )
- [x] All tests are green (@sayanchowdhury)
- [x] Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None` (@sayanchowdhury )
- [x] QA: check diff for image file list, packages, and image size in the image job output (@sayanchowdhury )
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury )
- [x] Update payload signed/uploaded (@tormath1 / @dongsupark )
- [x] `scripts` release created on GitHub (@sayanchowdhury )
- [x] Release job `container/release` ran (@sayanchowdhury )
- [x] Images uploaded with `copy-to-origin.sh` (@sayanchowdhury )
- [x] Azure offer updated & publishing started ()
- [x] Azure Go Live ()
- [x] GCP offers updated (@sayanchowdhury )
- [x] Symlink to "current" updated with `set-symlink.sh` (@sayanchowdhury )
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@sayanchowdhury )
- [x] Release package published in Nebraska (@tormath1 )
- [x] Send announcement to Mailing Lists (@tormath1 @pothos)
- [x] Send Tweet out (@miao0miao, @ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel (@flatcar/flatcar-maintainers )

**Comment by MWL88** [comment]
Hi, please will someone advise when the tasks to update the Azure image offers and Azure Go-Live will be progressed. I noticed these tasks for the previous release (#899 ) are also still incomplete.

**Comment by sayanchowdhury** [comment]
Hi Mark,

We currently publish Flatcar images through 5 Azure offers. Four of the offers are updated and live. We are facing issues with publishing the image to one of the offer with the offer id `flatcar-container-linux-free`. This offer is missing the last few releases and we are quite close on fixing the issue. 

If you are using any offer other than the one listed, it should have the updated image. Let me know if you have issues.

**Comment by MWL88** [comment]
Hi, thank you for the update. Yes I am using offer id `flatcar-container-linux-free`. How soon do you expect this issue to be resolved? Days or weeks? This will help me decide if I need to work around this image offer not being up to date.

Thanks

**Comment by sayanchowdhury** [comment]
I just published the first of the missing releases, so expect the missing images to be live before the start of next year.
