### ISSUE TITLE
Release Flatcar Container Linux Alpha 3493.0.0, Beta 3446.1.1, Stable 3374.2.3, LTS-2022 3033.3.9

### ISSUE THREAD

**Issue by dongsupark** [flatcar/Flatcar#952]
## Release Flatcar Container Linux Alpha 3493.0.0, Beta 3446.1.1, Stable 3374.2.3, LTS-2022 3033.3.9
  
The release of Flatcar Container Linux Alpha 3493.0.0, Beta 3446.1.1, Stable 3374.2.3, LTS-2022 3033.3.9 is planned for January 24th 2023. 

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [link](https://hackmd.io/W4EAN5BRShO0BlIRB0JdMw?view) (@dongsupark)
- [x] All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems (@dongsupark)
- [x] Branch off main (only new major) (@dongsupark)
- [x] Tag build branch (@dongsupark)
- [x] Start Jenkins builds, post links as comment (@dongsupark)
- [x] Test status captured in hackmd doc (@dongsupark)
- [x] All tests are green (@dongsupark)
- [x] Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None` (@dongsupark)
- [x] QA: check diff for image file list, packages, and image size in the image job output (@dongsupark)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@dongsupark)
- [x] Update payload signed/uploaded (@dongsupark)
- [x] `scripts` release created on GitHub (@dongsupark)
- [x] Release job `container/release` ran (@dongsupark)
- [x] Images uploaded with `copy-to-origin.sh` (@dongsupark)
- [x] Azure offer updated & publishing started (@pothos)
- [x] Azure Go Live (@pothos)
- [x] GCP offers updated (@dongsupark)
- [x] Symlink to "current" updated with `set-symlink.sh` (@dongsupark)
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@dongsupark)
- [x] Release package published in Nebraska (@dongsupark)
- [x] Send announcement to Mailing Lists (@miao0miao @jepio)
- [x] Send Toot out (@ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel (@dongsupark)

**Comment by dongsupark** [comment]
* Alpha 3493.0.0: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/549/cldsv/
* Beta 3446.1.1: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1140/cldsv/
* Stable 3374.2.3: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1139/cldsv/
* LTS 3033.3.9: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1138/cldsv/

**Comment by dongsupark** [comment]
FTR, image changes of Alpha 3493.0.0 (since 3480.0.0):

* amd64
```
 -Usr: 1144 MiB
 +Usr: 1163 MiB
```
* arm64
```
 -Usr: 1088 MiB
 +Usr: 1187 MiB
```
More or less the same as https://github.com/flatcar/portage-stable/pull/401.

**Comment by pothos** [comment]
Azure offers are done but the new Shared Image Galleries not yet.

**Comment by pothos** [comment]
> Azure offers are done but the new Shared Image Galleries not yet.

Done (This is Stable amd64 only)

**Comment by dongsupark** [comment]
GCP published. All done.
