### ISSUE TITLE
Portage-stable full alignment with Gentoo upstream / GH actions for package updates

### ISSUE THREAD

**Issue by t-lo** [flatcar/Flatcar#96]
**Issue**
- Portage-stable repo contains plain copies of Gentoo upstream recipes
- Some packages still significantly outdated
- Some of the build tooling (eclasses, python, etc) still significantly outdated

**Impact**
- No direct benefit from Gentoo upstream work
- Manual maintenance / copy+paste work necessary to upgrade packages

**Ideal future state**
- `portage-stable` is a zero-touch fork of gentoo upstream and we update by forward-winding `portage-stable` to new gentoo upstream commit IDs
- GH Actions are in place to upgrade packages as soon as upgrade is available in upstream Gentoo (similarly to existing kernel, rust, systemd automation)

Related issues:
- [x] https://github.com/kinvolk/Flatcar/issues/428

Initial TODO list:
- [x] move out all custom things out from portage-stable into coreos-overlay #646
- [x] update packages in portage-stable to be outdated at most by a revision, not version or suffix - #645
- [ ] prepare an initial automation for updating forked packages in coreos-overlay based on our gentoo snapshot #648
- [x] come up and implement solution for /etc handling with vanilla packages #647
- [x] prepare an initial automation splitting gentoo snapshot update into interesting and not-interesting parts #649
