### ISSUE TITLE
Release Flatcar Container Linux Beta 3493.1.0, Stable 3374.2.4

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#960]
## Release Flatcar Container Linux 3493.1.0, Stable 3374.2.4
  
The release of Flatcar Container Linux 3493.1.0, Stable 3374.2.4 is planned for February 16, 2023. 

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/7LAd93XORNGdoig6mJ-vtA?both) created from previous one for test tracking and release notes: [link](https://hackmd.io/7LAd93XORNGdoig6mJ-vtA?both) (@sayanchowdhury)
- [x] All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems (@dongsupark)
- Branch off main (only new major) (x)
- [x] Tag build branch (@dongsupark)
- [x] Start Jenkins builds, post links as comment (@dongsupark)
- [x] Test status captured in hackmd doc (@sayanchowdhury)
- [x] All tests are green (@sayanchowdhury, @dongsupark)
- [x] Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None` (@sayanchowdhury)
- [x] QA: check diff for image file list, packages, and image size in the image job output (@sayanchowdhury)
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury)
- [x] Update payload signed/uploaded (@dongsupark))
- [x] `scripts` release created on GitHub (@dongsupark)
- [x] Release job `container/release` ran (@dongsupark)
- [x] Images uploaded with `copy-to-origin.sh` (@dongsupark)
- [x] Azure offer updated & publishing started (@sayanchowdhury )
- [x] Azure Go Live (@sayanchowdhury )
- [x] GCP offers updated (@sayanchowdhury )
- [x] Symlink to "current" updated with `set-symlink.sh` (@dongsupark)
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@dongsupark)
- [x] Release package published in Nebraska (@dongsupark)
- [x] Send announcement to Mailing Lists (@tormath1)
- [x] Send Tweet out (@ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel (@tormath1)

**Comment by dongsupark** [comment]
Jenkins builds:
* Beta 3493.1.0: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/638/cldsv/
* Stable 3374.2.4: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/1294/cldsv/

**Comment by seh** [comment]
Per [discussion in the "flatcar" channel](https://kubernetes.slack.com/archives/C03GQ8B5XNJ/p1677248642556249?thread_ts=1676560434.431419&cid=C03GQ8B5XNJ) of the "Kubernetes" Slack workspace, I noticed that the Beta channel's AMI for version 3493.1.0 is available for now only in AWS's "us-west-2" region, instead of in twenty-one regions like the Stable and Alpha channels' AMIs.

Do you still intend to copy the Beta channel's image around to the other regions?

**Comment by ahrkrak** [comment]
resolved on Slack https://kubernetes.slack.com/archives/C03GQ8B5XNJ/p1677295300984799?thread_ts=1676560434.431419&cid=C03GQ8B5XNJ
