### ISSUE TITLE
Release Flatcar Container Linux Alpha 3549.0.0

### ISSUE THREAD

**Issue by sayanchowdhury** [flatcar/Flatcar#977]
## Release Flatcar Container Linux Alpha 3549.0.0

The release of Flatcar Container Linux the following channels is planned for March 20th, 2023.

- Alpha 3549.0.0

### Tasks
- [x] Go / No Go [hackmd doc](https://hackmd.io/team/flatcar?nav=overview) created from previous one for test tracking and release notes: [link](https://hackmd.io/4pWbBYPzSISE94TYsLiokg) (@sayanchowdhury)
- [x] Check that the kernel PR are merged for the channel(s) to be released. (@sayanchowdhury )
- [x] All planned changes are merged & blocker bugs are fixed, last nightly reviewed for problems (@sayanchowdhury )
- [x] Branch off main (only new major) (@sayanchowdhury )
- [x] Tag build branch (@sayanchowdhury )
- [x] Start Jenkins builds, post links as comment (@sayanchowdhury )
- [x] Test status captured in hackmd doc (@sayanchowdhury )
- [x] All tests are green (@sayanchowdhury )
- [x] Release notes / announcements added to Go/No Go doc from `container/image_changes` job by selecting `Timestamps: None` (@sayanchowdhury )
- [x] QA: check diff for image file list, packages, and image size in the image job output (@sayanchowdhury )
- [x] Matrix Go/No Go meeting (inc. release notes review) (@sayanchowdhury )
- [x] Update payload signed/uploaded (@tormath1)
- [x] `scripts` release created on GitHub (@sayanchowdhury )
- [x] Release job `container/release` ran (@sayanchowdhury )
- [x] Images uploaded with `copy-to-origin.sh` (@sayanchowdhury )
- [x] Azure offer updated & publishing started (@sayanchowdhury )
- [X] Azure Go Live (@t-lo )
- [x] GCP Offer deployment package uploaded to Google bucket and submitted for verification (@sayanchowdhury )
- [x] GCP Offer submit for verification (@sayanchowdhury )
- [x] GCP Offer Publish (@sayanchowdhury, @dongsupark )
- ~For new Stable: Manually run `./azure-sig.sh` to create new Shared Community Gallery Images~
- ~For new Stable: build and provide images for supported Cluster API providers~
- [x] Symlink to "current" updated with `set-symlink.sh` (@sayanchowdhury )
- [x] Website updated with `./update-flatcar-versions.sh` and PR merged (@sayanchowdhury )
- [x] Release package published in Nebraska (@tormath1)
- [x] Send announcement to Mailing Lists (@sayanchowdhury )
- [x] Send Tweet out (@miao0miao, @ahrkrak)
- [x] Brief version announcement in slack (k8s slack #flatcar) and the Flatcar matrix channel (@sayanchowdhury)

**Comment by sayanchowdhury** [comment]
CI [#715](http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/715/cldsv/) Jenkins build failed and been fixed in https://github.com/flatcar/coreos-overlay/pull/2543

CI Running http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/720/cldsv/

**Comment by sayanchowdhury** [comment]
Flatcar website PR: https://github.com/flatcar/flatcar-website/pull/260
